### ISSUE TITLE
Consider proxy when caching a stream

### ISSUE THREAD

**Issue by cfal** [algesten/ureq#109]
It looks like PoolKeys only consider host and port, which can lead to problems if a proxy is being used as a gateway to internal addresses - eg. proxy1 connects to 1.2.3.4 in a private network, proxy2 connects to 1.2.3.4 in another private network. Another (perhaps more limiting) option might be to make proxies agent-scoped, so that different connection pools are used.

**Comment by jsha** [comment]
Good catch! I think it's reasonable to make proxy part of PoolKey. Scoping proxies to agents is appealing, but that would require an API break for something that's just as easily solved internally.

**Comment by algesten** [comment]
Yeah I agree. We should put proxy into the pool key.
