### ISSUE TITLE
Allow saving multiple streams with the same address to the pool

### ISSUE THREAD

**Issue by cfal** [algesten/ureq#110]
It would be useful to be able to save multiple streams to the same address in the connection pool - for example, when doing chunked downloading via Range header, multiple connections can be used and reused.

**Comment by cfal** [comment]
Would a PR for this be accepted? I have a small change that does this but removed the MAX_IDLE_CONNECTIONS constant and added constants MAX_IDLE_HOSTS and MAX_IDLE_CONNECTIONS_PER_HOST. Could set this to 100 and 1 respectively by default to keep the behavior the same. But then it could also be nice to make these values configurable.

**Comment by algesten** [comment]
I think that's a good change! PR sounds good!
