### ISSUE TITLE
add API to conveniently return an error (even if it's just a 4xx/5xx response)

### ISSUE THREAD

**Issue by BurntSushi** [algesten/ureq#125]
Apologies if I've missed it in your API, but it would be very convenient to have a simple API that yields an error if an HTTP response isn't successful, including 4xx or 5xx status codes. Kind of similar to [reqwest's `error_for_status`](https://docs.rs/reqwest/0.10.7/reqwest/struct.Response.html#method.error_for_status) method.

Otherwise, error handling for common cases where I just want to return an error if the response is bad ends up being a bit tedious:

```rust
let resp = ureq::get(&url).call();
if let Some(err) = resp.synthetic_error() {
    bail!("bad HTTP communication: {}", err);
}
if resp.error() {
    bail!(
        "bad HTTP response from server: {} {}",
        resp.status(),
        resp.status_text()
    );
}
// okay, now we can read from `resp`
```

(And in particular, notice that I cannot do `return From::from(err);` to handle the synthetic error, since there is no way as far as I can see to obtain an owned `Error` value from the API.)

I think it would be nice if I could just do something similar to reqwest's API:

```rust
let resp = ureq::get(&url).call().error_for_status()?;
// okay, now we can read from `resp`
```

**Comment by BurntSushi** [comment]
Awesome crate by the way. I replace reqwest 0.9 with this crate and my dependency tree went from 200 to 100 dependencies. :-)

**Comment by jsha** [comment]
Glad you like the crate!

There's currently no Result-based API, but we've been talking about adding one. It's good to know there's demand. And the `error_for_status` pattern seems like an interesting one. I had been thinking that `call()` would return `Result<Response, Error>`, and that 5xx and 4xx statuses would be handled separately. I suppose we could still have that, like:

```
let resp = ureq::get(&url).call()?.error_for_status()?;
```

**Comment by BurntSushi** [comment]
Yeah, that would work too I think! I wasn't sure how important it was to be able to actually have a `Response` even if a synthetic error occurred. But I think as long as there's some convenient way to propagate an error, I'd be happy. :-)

**Comment by algesten** [comment]
Closing since this API is revised with ureq 2.0.

The relevant parts are to either match out error codes from `Error`: https://docs.rs/ureq/2.0.2/ureq/enum.Error.html#examples

Or alternatively turn the entire `Error` back into a `Response` using `OrAnyStatus`: https://docs.rs/ureq/2.0.2/ureq/trait.OrAnyStatus.html#tymethod.or_any_status
