### ISSUE TITLE
Cookie implementation uses one Header per Cookie instead of one Header for all Cookies

### ISSUE THREAD

**Issue by cazgp** [algesten/ureq#129]
RFC 6265 (https://tools.ietf.org/html/rfc6265#section-4.2) defines setting cookies in a request as:

4.2.  Cookie

4.2.1.  Syntax

   The user agent sends stored cookies to the origin server in the
   Cookie header.  If the server conforms to the requirements in
   Section 4.1 (and the user agent conforms to the requirements in
   Section 5), the user agent will send a Cookie header that conforms to
   the following grammar:

   cookie-header = "Cookie:" OWS cookie-string OWS
   cookie-string = cookie-pair *( ";" SP cookie-pair )

Note that this is defined as one Cookie header separated by ';'.

**Comment by jsha** [comment]
Good find! There's actually an even stronger requirement to not generate multiple Cookie headers:

https://tools.ietf.org/html/rfc6265#section-5.4
>    When the user agent generates an HTTP request, the user agent MUST
>   NOT attach more than one Cookie header field.
