### ISSUE TITLE
Please implement forms with application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by pozix604** [algesten/ureq#13]
While the library does many things without the dependency baggage, this one feature is crucial for many uses of post. Not supporting it precludes usage of this library. 

Please consider expediting.

**Comment by lolgesten** [comment]
Agree. It would be nice. I haven't got time to fix it right now. PR very welcome!

**Comment by dnlserrano** [comment]
FWIW, I'm currently using `serde_qs` to achieve this. Probably not worth bringing that dependency into the `ureq` crate itself though? I'm doing something along these lines:

```rust
let url = format!("https://myurl.com");
let request = MyRequest::new();
let urlencoded = serde_qs::to_string(&request).unwrap();
let response = ureq::post(&url)
    .set("Content-Type", "application/x-www-form-urlencoded")
    .send_string(&urlencoded);
```

For this to work,  the `request` instance needs to `#[derive(Serialize, Deserialize)]`. This is fairly straightforward to do when using `serde`, and it provides ways of ser/deserializing the most common Rust types [out of the box](https://serde.rs/#data-structures).

**Comment by bbx0** [comment]
That is a good hint @dnlserrano. As qstring is already a dependency a similar solution without serde  is easily possible (but also without serialization).

```rust
let urlencoded = format!("{}",
                qstring::QString::new(vec![
                    ("param1", "foo"),
                    ("param2", "bar"),
                ])
            );
let response = ureq::post(BASE_URL)
                .set("Content-Type", "application/x-www-form-urlencoded")
                .send_string(&urlencoded);
```

Maybe something like that is already sufficient for the most use cases. Works fine for my test case at least.
```rust
/// Send parameter as form data.
///
/// The `Content-Type` header is implicitly set to application/x-www-form-urlencoded.
///
/// ```
/// #[macro_use]
/// extern crate ureq;
///
/// fn main() {
/// let r = ureq::post("/my_page")
///     .send_form(vec![("foo", "bar"),("foo2", "bar2")]);
/// println!("{:?}", r);
/// }
/// ```
pub fn send_form<S, T>(&mut self, params: Vec<(S, T)>) -> Response
where
    S: Into<String>,
    T: Into<String>,
{
    self.set("Content-Type", "application/x-www-form-urlencoded")
        .send_string(format!("{}", QString::new(params)).as_ref())
}
```

**Comment by lolgesten** [comment]
I'd say both of these variants would be welcome additions The non-extra-dep as part of standard API and the serialize as a feature.
