### ISSUE TITLE
Publish new version of the ureq crate

### ISSUE THREAD

**Issue by nviennot** [algesten/ureq#134]
Hello Martin,

Do you mind releasing a new version of ureq?
Right now the rustls dependency is `^0.17` on the published ureq vrsion, preventing using the faster rustls `0.18` (semver before 1.x.x makes no compatibility assumptions, and thus cargo won't allow using rustls 0.18).

Thank you,
Nico

**Comment by algesten** [comment]
@nviennot You're right! I think it's about time. I've set the wheels in motion.

**Comment by algesten** [comment]
Sorted

**Comment by nviennot** [comment]
Thank you Martin
