### ISSUE TITLE
Improvements to redirects

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#152]
From https://github.com/algesten/ureq/pull/132#commitcomment-42273336, I started looking at how other HTTP clients handle redirects, and found some interesting things that we may want to consider for ureq:
edirect handling.

Python requests says: https://requests.readthedocs.io/en/master/user/quickstart/#custom-headers
> Authorization headers will be removed if you get redirected off-host.

It also has a `history` field: https://requests.readthedocs.io/en/master/user/quickstart/#redirection-and-history
> The Response.history list contains the Response objects that were created in order to complete the request. The list is sorted from the oldest to the most recent response.

And for some reason (I don't know why), requests disables redirects on HEAD by default.

Java HttpClient has a [redirect policy enum](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.Redirect.html), with values ALWAYS, NEVER, and NORMAL (which follows redirects, but does not allow downgrades from HTTPS to HTTP).

curl defaults to a redirect limit of 50; 10 and 5 are also common limits. [RFC 7231 says](https://tools.ietf.org/html/rfc7231#page-55):

      Note: An earlier version of this specification recommended a
      maximum of five redirections ([RFC2068], Section 10.3).  Content
      developers need to be aware that some clients might implement such
      a fixed limitation.

**Comment by jsha** [comment]
About copying headers on redirects: There's some very useful conversation with links to resources in https://github.com/golang/go/issues/4800. Go's `net/http` copies headers across redirects, *except* `Authorization`, `Www-Authenticate`, `Cookie`, and `Cookie2`: https://github.com/golang/go/blob/92c732e901a732855f4b813e6676264421eceae9/src/net/http/client.go#L962-L984. Those headers are copied only on redirects to the original host or subdomains. I don't see any logic about protocol downgrades (HTTP->HTTPS) but haven't yet looked very hard. There's also some special logic about when to preserve the Host header: https://github.com/golang/go/blob/92c732e901a732855f4b813e6676264421eceae9/src/net/http/client.go#L645-L651. Curl appears to do similar, but I couldn't find the relevant code: https://ec.haxx.se/http/http-redirects#redirecting-to-other-host-names.

I'm inclined to do similar, but leave out the subdomain logic, and make sure we drop sensitive headers on downgrade. And not implement the special Host logic. In other words: headers are generally preserved on redirects; sensitive headers are only preserved on redirects to the same origin (protocol + hostname).

**Comment by algesten** [comment]
> I'm inclined to do similar, but leave out the subdomain logic, and make sure we drop sensitive headers on downgrade. And not implement the special Host logic. In other words: headers are generally preserved on redirects; sensitive headers are only preserved on redirects to the same origin (protocol + hostname).

Thanks for looking into this. It all sounds reasonable. Let's do it.

**Comment by algesten** [comment]
I believe we have addressed this in issue #442 and PR #445 

We can add additional config options to the new AgentBuilder enum controlling this (like `ALWAYS`).
