### ISSUE TITLE
Fields copied from Request to Unit

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#155]
Reading through https://github.com/algesten/ureq/pull/148, I noticed that Unit makes a copy of a lot of fields that are present on Request:

            url: url.clone(),
            timeout_connect: req.timeout_connect,
            timeout_read: req.timeout_read,
            timeout_write: req.timeout_write,
            method: req.method.clone(),
            proxy: req.proxy.clone(),

But Unit already has a reference to Request. What do you think of removing these fields and delegating accesses to them to `unit.req` instead? Could save a bit of copying and memory use, but more importantly it could make it clearer where these fields are ultimately coming from.

**Comment by algesten** [comment]
Sounds good! I'm not even sure why it is like this.
