### ISSUE TITLE
Make 'cookie' optional

### ISSUE THREAD

**Issue by orf** [algesten/ureq#16]
Is it possible to make the `cookie` dependency optional? When making server-to-server requests it's not often that you use cookies, and the `cookie` dependency brings in quite a few others:

```
│   ├── cookie v0.12.0
│   │   ├── time v0.1.42
│   │   │   └── libc v0.2.65 (*)
│   │   │   [dev-dependencies]
│   │   │   └── winapi v0.3.8
│   │   └── url v1.7.2
│   │       ├── idna v0.1.5
│   │       │   ├── matches v0.1.8
│   │       │   ├── unicode-bidi v0.3.4
│   │       │   │   └── matches v0.1.8 (*)
│   │       │   └── unicode-normalization v0.1.8
│   │       │       └── smallvec v0.6.10
│   │       ├── matches v0.1.8 (*)
│   │       └── percent-encoding v1.0.1
```

So, would it be acceptable to add a `cookie` feature (enabled by default perhaps) that disables this dependency?

**Comment by lolgesten** [comment]
That would be nice! For backwards compat, the default should probably still have cookies, but it could be opted out of.
