### ISSUE TITLE
API changes for 2.0.0

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#174]
In #132, we've been discussing an API change to return Result<Response> in places where we currently return Response. That's a significant breaking change, so we'll want to cut a major version - 2.0.0.

We probably don't want to change the API *too* much since it will inhibit switchover, but cutting a new major version does present a rare opportunity to make changes that might be too disruptive at other times. @algesten, do you have any things you've been wanting to change?

I have one in particular: I'd like to change the `into_reader`, `into_string`, etc functions into something that doesn't consume the Response. Right now there's an awkward ordering requirement that's not strictly necessary:

```
// doesn't work
let resp = ureq::get("http://example.com/").call();
let body = resp.into_reader();
println!("received response code {}", resp.status());
```

```
// works
let resp = ureq::get("http://example.com/").call();
println!("received response code {}", resp.status());
let body = resp.into_reader();
```

I'm thinking something like `take_reader()`, which sets resp.stream to None. What do you think? The corresponding `take_string()`, `take_json()` names would be kind of awkward, unfortunately. Perhaps `body_reader`, `body_string`, `body_json`?

**Comment by jsha** [comment]
Oh another possibility: We could define a `struct Body` that encapsulates the stream, and a `Response.body()` method that returns an owned Body (taking the Stream out of the Response) and offers methods for the various types of output we want. So a call would look like:

```
let resp_json = ureq::get("http://example.com/")
  .call()?
  .body()
  .json();
```

**Comment by algesten** [comment]
> do you have any things you've been wanting to change?

Can't think of any at the top of my head. I'll review the API. A dream rewrite would ditch ureq's Request, Response types and base off the http crate, but that's a big breaking change.

>  I'd like to change the into_reader, into_string, etc functions into something that doesn't consume the Response.

The [http crate](https://docs.rs/http/0.2.1/http/) does this pretty well by having `Response<T>`. In hreq, I think that worked really well. There's [`Body`](https://docs.rs/hreq/0.7.0/hreq/struct.Body.html) struct with many different convenience ways of constructing/reading. The response is then always `Response<Body>` and what typically happens is this code:

```rust
let (parts, body) = response.into_parts();

let txt = body.read_to_string().await.unwrap();

assert_eq!(parts.status, 200);
```

Maybe we can do something similar?

```rust
let response = ureq::get("https://asdqwe");

// here we could keep backwards compat/convenience to grab 
// body straight off response. internally
// it just proxies to the new ureq::Body type.
// let reader = response.into_reader();
// let json = response.into_string();

// this is new API that separates the status/headers from body.
// Type signaure is ureq::Response::split(Self) -> (ureq::Headers, ureq::Body)
let (headers, body) = response.split();

let json = body.read_to_string().unwrap();

assert_eq!(headers.status, 200);
assert_eq!(headers.get("content-type").unwrap(), "application/json");
```

`Headers` might be a bit misleading as a name. 🚲🏠  ahead. It's like `StatusAndHeaders` which is a bit long.

**Comment by algesten** [comment]
@jsha throwing this into the mix:

One idea would be to rewrite some things from the ground up.

* Ergonomics
* Spec correctness
* Better layering

--- 

In my work on hreq, I did this [hreq-h1](https://github.com/algesten/hreq-h1). I think it's a pretty clean way of writing the layers of an http1.x client – i.e. make a lower layer that is only concerned with transport. Chunked, content-length (and socket close in the case of http 1.0) and connection keep-alive.

**Comment by Shnatsel** [comment]
Various timeout methods right now accept `u64` in milliseconds; instead they should accept a `Duration`.

While we're at it, https://docs.rs/ureq/1.5.1/ureq/struct.Request.html#method.timeout currently accepts a `Duration`, but it _might_ be a better idea to pass a deadline via type `Instant` directly, since IIRC that's what's used internally anyway and some people are advocating for deadlines as an API design choice, see https://gist.github.com/alkis/9510a840f1965185ab0a02cb59761dd8 and its discussion [here](https://www.reddit.com/r/rust/comments/8b5krv/the_case_for_deadlines/). But I'm not 100% convinced on this point.

**Comment by jsha** [comment]
@algesten I started a `release-2.0` branch to start staging these changes, and changed the base of #132 to it.

**Comment by jsha** [comment]
@Shnatsel :

> While we're at it, https://docs.rs/ureq/1.5.1/ureq/struct.Request.html#method.timeout currently accepts a Duration, but it might be a better idea to pass a deadline via type Instant directly, since IIRC that's what's used internally anyway and some people are advocating for deadlines as an API design choice, see https://gist.github.com/alkis/9510a840f1965185ab0a02cb59761dd8 and its discussion here. But I'm not 100% convinced on this point.

I think there are good use cases for both: A timeout is useful when you're, e.g. crawling a bunch of URLs and don't care how long they take in aggregate but don't want any one of them to take too much time. A deadline is useful when you're making a request as part of a larger workflow that already has a deadline, and you want to limit the request to that deadline.

Go's Context manages this nicely by offering both timeout and deadline settings, with timeouts automatically turned into deadlines internally. I think that's a good option for us, but since it would be a new function name for the new type, it's something we can add later as a non-breaking change. I don't think it needs to be on the list for 2.0.

**Comment by jsha** [comment]
A couple more thoughts:

Maybe `cookie` should not be part of the optional dependencies? Cookie storage is actually pretty rare to be on by default in non-browser clients. Between `cookie` and `json` I'd kind of expect `json` to be default and `cookie` not. That's because IME many projects already depend on serde_json, particularly projects that interact with web APIs (which ureq is particularly well suited for).

The methods that take a Url should take a `TryFrom<Url>` (which is implemented for &'a str), so users can pass either a str or an already-passed URL at their convenience. Note that we should document this well. When I was a beginner at Rust I found `TryFrom<Foo>` arguments very opaque. Actually to this day I still find it hard to figure out all the possible types a TryFrom is implemented for.

**Comment by jsha** [comment]
Another theme for 2.0: So far we've had a number of options that exist only on Request, but also make sense on Agent. In some cases they make _more_ sense on Agent. For instance, we recently gave Agent a `set_tls_config` and `set_proxy`. There are some others that should also be added to Agent: timeout, timeout_read, timeout_write, timeout_connect, redirects.

One option would be to put all of these settings on Agent, and remove them from Request. I kind of like that for simplicity reasons - there's just one way to do things. In the case where you only want to make one request and don't care about saving the agent, that could look like:

```rust
let resp = ureq::AgentBuilder::new()
    .proxy("http://example.com")
    .timeout(Duration::from_secs(1))
    .build()
    .get("http://example.net")?;
```

Another option, if we want to preserve the Request-centric APIs for these, would be to create RequestBuilder (which we probably want to do anyhow), and have each RequestBuilder contain `Either<Agent, AgentBuilder>`. For all the settings whose "true home" is on Agent, the corresponding method on `RequestBuilder` would simply forward to the same-named method on that `RequestBuilder`'s `AgentBuilder`.

**Comment by algesten** [comment]
@jsha The stuff that needs to be on Request is only _reasonable defaults_. I.e. to quickly fire off a request is just `ureq::get("http://example.net")?;`, and that is done with good defaults. I've been mostly looking at [superagent's API](https://github.com/visionmedia/superagent), which in turn often use nodejs defaults.

These could be moved to agent (or builder of agent):

* all timeouts
* `set_tls_config`
* `set_proxy`

We might want to quickly research whether curl, go etc have default timeouts.

**Comment by jsha** [comment]
Go has a default connect timeout of 30 seconds and a TLS handshake timeout (which we're not planning to implement) of 10 seconds. It does not implement a per-read timeout, but offers a "ReadTimeout" and a "WriteTimeout" that apply to the entire write phase or read phase of the request. I.e., they act more like our overall `timeout()`.

[curl has a default connect timeout of 300 seconds](https://curl.haxx.se/libcurl/c/CURLOPT_CONNECTTIMEOUT.html) and an [overall timeout, which has no default](https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html). It does not appear to offer a per-read timeout. Instead it has [LOW_SPEED_TIME](https://curl.haxx.se/libcurl/c/CURLOPT_LOW_SPEED_TIME.html) and [LOW_SPEED_LIMIT](https://curl.haxx.se/libcurl/c/CURLOPT_LOW_SPEED_LIMIT.html), which will abort connections below a certain speed; that can be used to achieve the same goal we have, of allowing connections that have silently gone dead to be detected.

**Comment by algesten** [comment]
@jsha Regarding `TryFrom<Url>`. I think it's easier to read `Into<Url>`. And I agree it might be harder to read. I'm in two minds. I deliberate made all url params as `&str`, cause I want the API to be obvious. I could be moved on this, but at the same time, I think it's important we delay the potential error that arises here.

I.e. I think we could consider this change:

```rust
pub fn get(path: &str) -> Request { … }
```

Change to:

```rust
pub fn get(path: impl Into<Url>) -> Request { … }
```

But I don't want us to go:

```rust
pub fn get(path: impl Into<Url>) -> Result<Request> { … }
```

There is one "error boundary" which is `Request::call()` (or the equivalent send body methods). I don't want to spread that error to other places. This is an area where I feel ergonomics goes before correctness. A similar situation is for headers:

```rust
pub fn set(mut self, header: &str, value: &str) -> Self { … }
```

Not all `&str` are valid header key/values, however for both URL and headers, the chances of a handling invalid URL or headers must be considered quite rare. Hence I don't want the API to enforce correctness at this point,
but we "delay" it to the `.call()` as a catch-all for all things that might go wrong.

**Comment by jsha** [comment]
> Regarding TryFrom<Url>. I think it's easier to read Into<Url>

I actually wrote this wrong. The type we would consume is `TryInto<Url>`; Url implements `TryFrom<&str>`. Unfortunately there's no `Into<Url>` variant because parsing can fail.

> I think it's important we delay the potential error that arises here.

Yep, I totally agree that we can and should delay the error until build time, the same way we do with `set`.

By the way, another thing I have been thinking about is trimming some of the functions named after HTTP method names: `trace`, `patch`, `options`, `delete`, maybe `put` and maybe `head`. Definitely we should keep `get` and `post`; those are extremely common and should have nice shortcuts. Reasoning: Some of those methods may be confusing to new users based on the name alone. Does `options` set options for ureq? Also, since they're used so rarely, it would be nice to delete them so the documentation is shorter and it is easier to find the "well-lit paths."

For comparison, Go's `net/http` offers shortcuts for GET, POST, and HEAD. Python Requests offers them for GET, POST, HEAD,  PUT, PATCH, and DELETE.

**Comment by jsha** [comment]
> I have one in particular: I'd like to change the into_reader, into_string, etc functions into something that doesn't consume the Response.

I was thinking about this problem today and realized it actually has several interrelated components:

Does Response automatically read the body?
Does Response own the body?
If Response owns the body, can it be taken out of the Response?
If the body can be taken out of the Response, is it into-style, take-style, or split-style?

Some use cases I can think of:

1. Small API responses
2. Continually streaming responses
3. Big downloads streaming straight to disk

For (1), it's would be convenient for ureq to automatically read the body (as `Vec<u8>`) and own it. That way, user code can parse it, or print it, or access fields, all using an `&` reference to the body. That means the user code can also read headers and other Response properties without worrying about ordering things so the header accesses come before the body accesses. One downside of returning a reference to a body: if, say, body_ref returns a reference to the body, something like `let x = ureq::get("http://example.com")?.body_ref()` would fail because of "temporary value dropped while borrowed." I.e. you'd have to assign the Response to a variable. That makes things less convenient so it can't be the common case.

For (2) and (3) the user needs access to a `Read` or `&mut Read`. If Response owns the `Read` and hands out `&mut Read` references, it would be possible for user code to accidentally get a partial body - for instance by getting a `&mut` to the body stream, reading some bytes, dropping the reference, and somewhere else getting `&mut` and reading more bytes. I think for these cases, it makes sense for the user code to take ownership of the body stream.

In terms of into vs take vs split:

Into has the advantage that you can use it in a chained statement like the above without problems from temporary variables. Also it enforces at build time that you can only get the body once. The disadvantage of into is that once you've called it, you can't access headers anymore.

Split has the advantage of enforcement at build time that you can only take the body once, and avoids the ordering problem, but comes at the cost of increased complexity - there are additional types to think about, and you have to decide whether to examine headers from the Request pre-split or from the StatusAndHeaders post-split. Since that's a distinction without a difference it'd be nice not to make people think about it.

Take fixes the ordering problem with regards to checking headers. The disadvantage is the it moves the compile-time check that you can only get a body once to a run-time check, and makes the caller deal with an `Option`, probably by calling `unwrap()`.

There's are a lot of variations we could offer as different options, but as always in keeping of the spirit of simplicity I think we should pick just a couple of good ones that allow expressing the most useful and important semantics.

For instance, we could offer `.body_ref() -> Result<&[u8]>`, which reads the body into a `Vec<u8>` owned by the `Response` and returns a reference to it. That would live alongside the current `into_string()` etc that consume the Response and are useful in chained statement.

**Comment by algesten** [comment]
@jsha 

I agree with all that you're saying.

> The disadvantage of into is that once you've called it, you can't access headers anymore.

This to me is not a big problem enough to dictate the direction of the API. Structs that "consume" the instance are very common, you just have to make sure you pick out the headers you're interested in before reading the body.

If we want be helpful, we could always still have a `StatusAndHeaders` which is `Clone` and have like:

```rust
impl Response {
  fn status_and_headers(&self) -> &StatusAndHeaders { … }
}
```

So if there is a use case for absolutely needing the headers after the body, one can do `resp.status_and_headers().clone()`

**Comment by Shnatsel** [comment]
> A dream rewrite would ditch ureq's Request, Response types and base off the http crate, but that's a big breaking change.

Consider also the http-types crate: https://docs.rs/http-types/

**Comment by algesten** [comment]
@Shnatsel  Yeah. I'm quite keen on using the http crate. My rewrite of ureq into an async [hreq](https://docs.rs/hreq/0.7.0/hreq/trait.RequestBuilderExt.html) uses extension traits to "enrich" the http crate with functions like `call()` and `send()`.

Wonder how much of a departure such an endeavour would be 🤔

**Comment by Shnatsel** [comment]
Note that `http-types` is a distinct crate from `http`.

Also, `http` unconditionally depends on `bytes` crate, which uses atomic reference counting and contains a lot of unsafe code, neither of which are called for. In single-threaded scenarios it might as well be slower than a straight-up `Vec`. I'm not sure how pervasive its use of `bytes` actually is in `http`; perhaps it can be feature-gated.

**Comment by algesten** [comment]
> Note that http-types is a distinct crate from http.

Yeah, I know. I'm in two minds about `http-types`. I think it's sad the rust echo system of "http standards" are split and I prefer the cleanliness of `http` crate not providing any concrete `Body` implementation focusing only on headers, url and request/response.

> Also, http unconditionally depends on bytes crate

I'm not a fan of the `bytes` crate, but not because I'm too worried about the unsafe – it's so thoroughly used throughout tokio/h2/hyper, and written by people I trust – it's more that I find the API awkward and I prefer vanilla std over it. Luckily `bytes` is an internal detail to the `http` crate, so it doesn't matter much for my use.

**Comment by jsha** [comment]
I actually would prefer to adopt neither `http` nor `http-types`. They don't bring us any cross-compatibility benefits, since no one needs to build a Request with ureq and then pass it to `reqwest` or `surf`. The main benefit we get from them is that we use pre-designed APIs, and share optimizations that other folks have done in those crates.

Those benefits come at a cost, though: We lose a lot of control over our own APIs. Since we care a lot about making this package very easy to use and simple, that's a big cost. Here's a concrete example: If you have a URL and want to add query parameters, in ureq you do:

```
let resp = ureq::get("http://example.com/path")
  .query("foo", "bar")
  .query("baz", "quux")?;
```

In `http` / `reqwest` I think it's something more like (I haven't tested this):

```
let url: Url = "http://example.com/path".parse()?
  .query_pairs_mut()
  .append_pair("foo", "bar")
  .append_pair("foo", "bar");
let resp = reqwest::get(url)?;
```

There's definitely something nice about the latter - it's using the already existing methods from the url crate rather than defining new ways to set query params. There's also something nice about our approach. But if we adopt the `http` crate (or `http-types`), we have to adopt all those small decisions.

I think the Rust http ecosystem is not so mature that we know for sure what interfaces are nicest, so I think it's valuable for us to have our own versions of `Request` and `Response` that we can iterate on more easily than if we consume them from the `http` crate.

**Comment by Shnatsel** [comment]
reqwest API in particular has been considered sufficiently user-hostile for people to write [their own HTTP clients atop Hyper](https://crates.io/crates/yukikaze) just to get a better API.

**Comment by algesten** [comment]
@jsha 

> Those benefits come at a cost, though: We lose a lot of control over our own APIs. Since we care a lot about making this package very easy to use and simple, that's a big cost.

I totally agree. This was after all a starting point for creating ureq – simplicity. Hyper got their strap line: "A fast and correct HTTP implementation for Rust." I care somewhat for fast, not so much for correct and above all for usable, which they left out. Hyper is lower level than reqwest, but the "correct" I think shines through in the higher APIs.  For example, in ureq I deliberately didn't do header key/value validation (that you've added), because if the user wants to use non-spec-compliant chars, what do I care?

I do however think I found a quite reasonable middle ground using extension traits. Notice that `hreq` uses the `http` crate and still have a ureq style [`.query()`](https://docs.rs/hreq/0.7.0/hreq/trait.RequestBuilderExt.html#tymethod.query).

But I'm not going to argue hard for using an external crate.

**Comment by jsha** [comment]
I think we're pretty close to being ready to release 2.0. I wanted to touch back on some of the main themes here:

 - `into` vs `take` vs `split`: We're going to keep the current approach, which uses `into*` to get the body. This doesn't solve the awkwardness of checking headers after calling `into*`, but we can solve that later with additions to the API.
 - Reading request bodies on error: We aren't going to fully solve this in the 2.0 release. Users can set `error_for_status(false)` and read bodies manually if they want; otherwise, connections will be unnecessarily dropped on errors. I think we will want to solve this down the road by automatically reading error bodies and returning the connection to the pool, if the body is < N bytes.

If there's anything else we need for 2.0, let's talk about it! I'd like to publish a release candidate next weekend.

**Comment by jsha** [comment]
Searching past pull request for "API break", I found this comment: https://github.com/algesten/ureq/pull/48#discussion_r407158015.

It mentions the possibility of changing all our `&str` arguments to `AsRef<str>`. That would allow us to take `String` as well as `&str`. For instance, it would be possible to do:

```
ureq::get(format!("http://example.com/api/{}/status.json", item))
```

Instead of:

```
ureq::get(&format!("http://example.com/api/{}/status.json", item))
```

Just wanted to check in, @algesten, on whether this is something you'd like to do for 2.0. I searched around for some thoughts on approaches here and found this forum thread: https://users.rust-lang.org/t/idiomatic-string-parmeter-types-str-vs-asref-str-vs-into-string/7934. I think on balance, sticking with `&str` fits ureq's beginner-friendly approach, where you don't have to know about types like `AsRef` to understand the function signatures.

(this issue and #235 were the only things I found in my search).

**Comment by algesten** [comment]
@jsha I'm quite partial to `&str` because exactly as you say, it's beginner friendly.

Since that discussion you linked, there's a new kid in town: `arg: impl Into<String>`. This one I quite like, cause the type signature is not that intimidating and much easier to understand than `T: Into<String>`. 

The advantage would of course be to avoid a forced extra allocation for each arg if the caller already have a String. 

I could be persuaded to change to `impl`, what do you think?

**Comment by jsha** [comment]
`impl Into<String>` sounds good. I also realized this would be a non-breaking change (since it expands the set of things accepted), so let's punt on it as part of the 2.0.0 milestone, and possibly do it after the release.

**Comment by algesten** [comment]
Sounds good!

**Comment by DoumanAsh** [comment]
As of one of these people who had to write new client on top of hyper and someone who avoids `http` and `bytes`
I would greatly prefer if `ureq` would continue to stick to owning all its primitives. (I use it in few of my simple utilities where I only need simple requests without concurrency)
Looking at code it is not much, and in addition to some unnecessary allocations there is nothing wrong with it as it is.

I had to fight through hyper's API precisely because of limitations imposed by `http` and `bytes`
It would be great if you'd keep dependencies only to necessary minimum.

**Comment by jyn514** [comment]
Since 2.0 has been published, I think this can be closed.
