### ISSUE TITLE
"socks-proxy" feature is undocumented

### ISSUE THREAD

**Issue by Shnatsel** [algesten/ureq#183]
Cargo.toml file includes a "socks-proxy" feature. However, there is no description of it in the README section on features, and there are no mentions of socks on docs.rs either.

**Comment by algesten** [comment]
Good point. We will fix that. Thanks!

**Comment by dfirence** [comment]
Hi, I would like to add proxy support to a tools I built. How can I use “ureq” to have proxy capabilities?

**Comment by algesten** [comment]
Hi @dfirence thanks for the reminder. Please see linked PR where I document the proxy support. We will bring the doc into the next release.

**Comment by dfirence** [comment]
Hey @algesten 

thank you! I really appreciate `ureq and the support for this feature thank you!
