### ISSUE TITLE
Build pattern on Agent

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#184]
Pulling out some conversation from https://github.com/algesten/ureq/pull/182#issuecomment-705667830:

> Perhaps build is now such a fuzzy topic that it should not exist at all.

@algesten, I'm thinking maybe this is the answer: that Agent shouldn't have a build. I've often found the .build method a bit confusing, since you can accomplish the same thing by just creating an agent and mutating it.

Alternately, we could decide we want to double down on the builder pattern and create a separate AgentBuilder type whose `.build()` returns an `Agent`. This could actually have some advantages, because we could say that certain options (like TLS config and resolver) can only be set once, when an Agent is first created. This saves some awkwardness like clearing the pool when those settings change.

Another thing of note: Right now we have a few setters on Agent that don't follow the chained method approach. We should probably clean that up if we stick with chained methods:

- set_max_pool_connections
- set_max_pool_connections_per_host
- set_cookie

(Also interesting to note, these all take `&self` rather than `&mut self`, which is made possible by interior mutability, but we should probably switch to `&mut self` for clarity and safety).

These are the existing setters that return `&mut Agent` or `&mut Self`:

- set
- auth
- auth_kind
- set_resolver
- set_proxy

Some various resources I looked up in trying to think about this:

https://randompoison.github.io/posts/returning-self/
https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
https://github.com/rust-unofficial/patterns/blob/master/patterns/builder.md
https://github.com/rust-unofficial/patterns/issues/64
https://en.wikipedia.org/wiki/Builder_pattern

/cc @rawler

**Comment by algesten** [comment]
Good observation!

Let's fix this for 2.0. I think we should either do a pure builder pattern or stop song chaining/build.

**Comment by jsha** [comment]
This is mostly complete in the `release-2.0` branch. One thing that still needs attention: `AgentBuilder.build()` is currently infallible. I think we should probably make it a `Result<Agent, Error>` for future proofing, in case we add some future field that might cause errors at build time. For instance, we might get a set_cookie call that is invalid in some way. [Currently CookieStore discards errors](https://docs.rs/cookie_store/0.12.0/src/cookie_store/cookie_store.rs.html#59-70), but we might want to do something different someday.

**Comment by jsha** [comment]
Thoughts on whether we should make `AgentBuilder.build()` fallible even though it doesn't currently fail? I'm leaning towards "what we have now, where it's infallible, is fine."

For comparison, I checked out reqwest and isahc, and they both have fallible agent builders. In reqwest, it looks like the failure paths are (a) initializing trustdns fails to load some config, and (b) some of the configuration methods automatically load certificates from disk, and that can fail. For isahc, the failure paths are (a) a default header was set but fails validation, and (b) isahc sets up a thread to communicate with curl, and some of the communication things can fail - like binding a UDP port.

If in the future we do add some fallible agent setup steps, we do have a possible hack: we could build an Agent that always returns Requests that immediately error. It's pretty ugly, since we'd be deferring errors rather than showing them as soon as possible.

**Comment by algesten** [comment]
Let's leave as is. I'm quite relaxed with bumping major again if need be.
