### ISSUE TITLE
Request::timeout methods should all take Duration as timeout argument

### ISSUE THREAD

**Issue by tgeoghegan** [algesten/ureq#185]
`Request` has a handful of methods for defining timeouts. [`timeout`](https://docs.rs/ureq/1.5.1/ureq/struct.Request.html#method.timeout) takes `core::time::Duration` but the other three take `u64` documented as the number of milliseconds. For consistency and clarity, all the timeout methods should take `core::time::Duration`.

**Comment by jsha** [comment]
Thanks for the report! I agree. We'll make this part of our [API changes for 2.0](https://github.com/algesten/ureq/issues/174).

**Comment by jsha** [comment]
Fixed on the 2.0 branch in #186.
