### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by akhilles** [algesten/ureq#19]
The Cargo manifest suggests that this project is dual licensed under MIT OR Apache-2.0. However, there are no LICENSE files and the README suggests it's only licensed under MIT.

If maximum compatibility with the Rust ecosystem is desired, I would follow the recommendations at https://rust-lang-nursery.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive.

**Comment by algesten** [comment]
Fixing. Thanks!
