### ISSUE TITLE
Creating testserver in doctests

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#204]
I've been working on getting our tests to run such that they always hit a local testserver rather than the network. That will make our tests more robust to network interruptions or getting throttled by example sites (which we've started to see in our test runs). Relatedly, as we move into 2.0, I'd like to add `?` in all our doctests that return a Result, since it's more realistic. Right now that would cause failed tests because many of our doctests fetch `/`; I'd like to change that to a real URL, but before we do that, I'd like to get the doctests talking to a local testserver.

So far, I've gotten our regular unittests working this way with `#[cfg(test)]`. The doctests are harder. For doctests, cargo builds the whole library as it would normally be built for consumption by the end user, and then separately builds and runs the doctests against that library. There is a recently-added `#[cfg(doctest)]`, but it doesn't behave the same way as `#[cfg(test)]`. It is only used when _finding_ doctests; it's not used when building the library.

So far it looks like there are two solutions, which are both a bit painful:

Solution 1: Define an undocumented public function that (a) spins up a testserver and (b) modifies a global Arc<Mutex<bool>> that tells the default AgentBuilder to set up a resolver that points at a testserver. For each doctest, in a `/// #` line above the main body, call that setup function. This is a little less painful than it sounds because if we want to use `?` in our doctests we will also need to add a `/// # fn main() -> Result<()> {` above each doctest.

Solution 2: As [suggested here](https://users.rust-lang.org/t/test-setup-for-doctests/50426/5), put a no_run attribute on the doctests, and copy their actual bodies into the `tests/` directory. I'd want some tooling to automate the process, since it's very convenient to write tests inline with the documentation, and I've found that our doctests catch a lot of bugs.

I'm leaning towards Solution 1.

**Comment by algesten** [comment]
And I'm leaning towards Solution 2 :)

For me, doc tests are first and foremost _documentation_. They should show exactly how to use `ureq` without any extra code lines that the user must ignore. `no_run` means we will still get the benefit of compilation, without actually executing.

I like the testserver you built, and I particularly like how you snuck it into `ureq::agent()`. Having our general tests without network connection is great, but I'm in two minds about the doc tests. I guess it comes back to my previous thought: they are first and foremost _documentation_. Realistic documentation is and overarching concern.

**Comment by jsha** [comment]
> without any extra code lines that the user must ignore.

That's the cool thing about `/// #` - those lines get hidden in the generated documentation: https://doc.rust-lang.org/rustdoc/documentation-tests.html#hiding-portions-of-the-example

**Comment by algesten** [comment]
`/// #` :o … I had no idea. Alright. Solution 1 is totally doable.

**Comment by jyn514** [comment]
> Solution 2: As suggested here, put a no_run attribute on the doctests, and copy their actual bodies into the tests/ directory. I'd want some tooling to automate the process, since it's very convenient to write tests inline with the documentation, and I've found that our doctests catch a lot of bugs.

If you're ok with using nightly, you could use `doc(include = "tests/x.rs")`: https://doc.rust-lang.org/nightly/rustdoc/unstable-features.html#include-external-files-as-api-documentation

**Comment by algesten** [comment]
@jyn514 Interesting! I [read](https://docs.rs/about/builds) that docs.rs runs nightly always, so that would be an option.

**Comment by jsha** [comment]
Done in release-2.0.
