### ISSUE TITLE
Update how we import json macro

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#208]
Right now serde_macros.rs says:

```
// this file is borrowed in its entirety until macro_reexport stabilizes.
// https://github.com/rust-lang/rust/issues/29638
```

That issue is closed in preference to https://github.com/rust-lang/rust/pull/49982, which links to https://github.com/rust-lang/rust/issues/35896. I'm not sure what the current status of everything is but I suspect we can update this.

**Comment by algesten** [comment]
Wel can! I was thinking about that today. We should be able to remove this file now.

**Comment by jsha** [comment]
Done in release-2.0 branch.
