### ISSUE TITLE
TLS "insecure" mode

### ISSUE THREAD

**Issue by btv** [algesten/ureq#210]
Hi & thank you for creating such an easy to use http client.

Its possible I missed it in the documentation, but is there a way to perform an insecure https connection? (Like using `-k` in curl.)

Thank you in advance for the help.

**Comment by jsha** [comment]
We don't currently support this, though there's a change in #121 to allow it.

Note that you can achieve this yourself by setting the TLS config to one that disables certificate checking.

**Comment by btv** [comment]
Thank you for the hint on how to do this, I appreciate the help. I'll close the issue.
