### ISSUE TITLE
Support HTTP/2. 

### ISSUE THREAD

**Issue by KlockiLego** [algesten/ureq#219]
Are there any plans to support HTTP / 2 specification ?

**Comment by jsha** [comment]
We haven't really talked about it. I'm somewhat interested, but it would take a while. Can I ask which features of HTTP/2 you are particularly interested in?

One of the big challenges of HTTP/2 in ureq's "no async" model is multiplexing multiple concurrent requests on a stream. I think we would wind up having to spawn a reader and writer thread for each stream, and have those threads communicate with others via channels or some other form of synchronization. Would definitely introduce a lot of (internal) complexity.

Another option would be to implement just the parts of HTTP/2 that don't require multiplexing across threads - for instance, compressed headers. We could even offer a "batch download" API if the user code has all the URLs ready up front. That in theory wouldn't require spawning threads.

**Comment by algesten** [comment]
As the browser world moves on to HTTP/3, I've become gradually more convinced that for 99% of server-server communication or server-API, developers are likely to stick with HTTP/1.1 for a long time yet. The multiplexing part of HTTP/2 or head-of-line blocking HTTP/3 solves (which is a consequence of the multiplexing), is largely hard optimzing for the browser use case (load all resources from a page at once). And ureq's main use case will be stuff like calling S3 or using some SAAS cloud API, in which case I suspect the benefits of HTTP/2-3 would be negligible.

> Would definitely introduce a lot of (internal) complexity.

ureq's internals are quite simple, at times even naive, which also makes it quite easy to hack – you don't have to be a super rust dev to understand what's going on and do a PR. The benefits of that weighs quite heavy against the complexity HTTP/2-3 would introduce. 

Never say never, but In short, I find it unlikely we would want to do HTTP/2-3 in ureq.

**Comment by jsha** [comment]
For what it's worth, there are some API use cases where HTTP/2 is really useful. For instance if you want to retrieve a large number of small API objects efficiently.

> ureq's internals are quite simple, at times even naive, which also makes it quite easy to hack – you don't have to be a super rust dev to understand what's going on and do a PR. The benefits of that weighs quite heavy against the complexity HTTP/2-3 would introduce.

👍🏻

**Comment by jsha** [comment]
Closing this out for now - thanks for the question!
