### ISSUE TITLE
I can't send cookies with Agent::set_cookie()

### ISSUE THREAD

**Issue by alexwlchan** [algesten/ureq#23]
**I'm using ureq 0.11.2, and I can't seem to set cookies on a request correctly.**

I have the following project:

```toml
# Cargo.toml
[package]
name = "ureq-cookies"
version = "0.1.0"
authors = ["Alex Chan <alex@alexwlchan.net>"]
edition = "2018"

[dependencies]
ureq = "0.11.2"
```

```rust
// main.rs
extern crate ureq;

fn main() {
    let agent = ureq::agent();
    
    let cookie = ureq::Cookie::new("name", "value");
    agent.set_cookie(cookie);
    
    let resp = agent.get("http://127.0.0.1:5000/").call();
  
    println!("{:?}", resp);
}
```

This code:

* Creates an agent
* Calls `set_cookie` to create a cookie `name=value`
* Makes a request to http://127.0.0.1:5000/

This is based on the example code given in https://github.com/algesten/ureq/blob/master/src/agent.rs#L189-L196

**I'd expect this snippet to send the cookie `name=value` to http://127.0.0.1:5000, but the server isn't receiving the cookie. Am I doing something wrong?**

If I set the Cookie header manually, the server does receive the cookie, but this seems to defeat the point of having a `set_cookie()` method:

```rust
extern crate ureq;

fn main() {
    let mut agent = ureq::agent();

    agent.set("Cookie", "name=value");
    
    let resp = agent.get("http://127.0.0.1:5000/").call();
  
    println!("{:?}", resp);
}
```

## Conjecture

This is the body of `set_cookie()`:

https://github.com/algesten/ureq/blob/da42f2ed8f16a8b7c08e436f54384d6e2a5e25b5/src/agent.rs#L199-L205

If it can't acquire the state as mutable, the cookie is quietly dropped. I wonder if that's what's happening here?

## How I'm inspecting the cookies

At http://127.0.0.1:5000, I'm running a small Python web server. On every request, it prints the headers and the cookies it received:

```python
#!/usr/bin/env python
# -*- encoding: utf-8

import flask

app = flask.Flask(__name__)


@app.route("/")
def index():
    print("\nGot a request!")
    print("Headers: %r" % dict(flask.request.headers))
    print("Cookies: %r" % flask.request.cookies)
    return "hello world"


if __name__ == "__main__":
    app.run(port=5000)
```

This is the output:

```
# Using set_cookie("name", "value")
Got a request!
Headers: {'Host': '127.0.0.1', 'User-Agent': 'ureq', 'Accept': '*/*'}
Cookies: {}

# Using set("Cookie", "name=value")
Got a request!
Headers: {'Host': '127.0.0.1', 'User-Agent': 'ureq', 'Accept': '*/*', 'Cookie': 'name=value'}
Cookies: {'name': 'value'}
```

**Comment by lolgesten** [comment]
Thanks! I'd need to look into this a bit later.

**Comment by jsha** [comment]
I believe you need to set the `domain` attribute of your cookie, otherwise it won't match the hostname of any request, and so won't be sent on any request. See documentation for setting domain on a cookie here: https://docs.rs/cookie/0.14.2/cookie/struct.Cookie.html#constructing-a-cookie.

**Comment by algesten** [comment]
I believe this works.
