### ISSUE TITLE
URL and method on errors

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#232]
I was just thinking - it would be useful if our Error type included the URL that was being request, and the method. That way instead of printing, e.g.

```
HTTP status 404
```

We could print

```
HTTP status 404 on GET http://example.com
```

The alternative would be for the caller to add the URL as context, but that would involve duplicating the URL in most cases.

**Comment by algesten** [comment]
Yeah. As long as we're not cloning that looks good!

**Comment by jsha** [comment]
Implemented in #234. I did wind up cloning the URL. I can probably find a way around it, but I think it would require changing the `Request::do_call` semantics to consume the request. Can you tell me more about what you meant by "as long as we're not cloning?"

**Comment by algesten** [comment]
Just felt it was wasteful to clone. Maybe a minor.

**Comment by jyn514** [comment]
Personally I don't think the clone is a big deal, the IO will take way longer than the `memcpy`.
