### ISSUE TITLE
Panic in ureq::stream::connect_https on some websites

### ISSUE THREAD

**Issue by Shnatsel** [algesten/ureq#24]
I've tested `ureq` by downloading homepages of the [top million websites](https://blog.majestic.com/development/majestic-million-csv-daily/) with it. I've found [a panic](https://github.com/briansmith/ring/issues/929) in `ring`, and 13 out of 1,000,000 websites triggered a panic in `ureq::stream::connect_https`.

Steps to reproduce: 
Run [this simple program](https://gist.githubusercontent.com/deltaphc/2949ed292c7d1169e744e5ffa7fd0687/raw/bb5e5f30bbfa38406a6bd7bd538224f450717db3/ureq_test.rs) with "yardmaster2020.com" given as the only command-line argument. 

The same website opens fine in Chrome. Full list of websites where this happens: amadriapark.com, bda.org.uk, egain.cloud, gdczt.gov.cn, hsu.edu.hk, mathewingram.com, roadrover.cn, srichinmoyraces.org, thetouchx.com, tradekorea.com, utest.com, wlcbcgs.cn, yardmaster2020.com

Backtrace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidDNSNameError', src/libcore/result.rs:1189:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:195
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:376
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1189
  14: ureq::stream::connect_https
  15: ureq::unit::connect_socket
```

**Comment by lolgesten** [comment]
Thanks! I'll follow the bug in ring and update when I can.

**Comment by Shnatsel** [comment]
I'm not sure if I made it clear, so just in case: there are two distinct panics, one in ring (assertion failure) and another one in ureq (unwrap).

**Comment by lolgesten** [comment]
Ah. Yes. The unwrap in ureq we should fix!

**Comment by cup** [comment]
> amadriapark.com

Im not sure all these should be working with Ureq. For example, the one ive quoted gives this with Firefox:

> Warning: Potential Security Risk Ahead
