### ISSUE TITLE
IPv6 Bind

### ISSUE THREAD

**Issue by GoldLine1337** [algesten/ureq#251]
Hello, I'm trying to bind a IPV6 address as ip source for an exampe to facebook.com

can you give me an example of the code?

**Comment by ycd** [comment]
I'd also love to have an example of this.

**Comment by algesten** [comment]
ureq connects to whatever socket address it gets [here](https://github.com/algesten/ureq/blob/ec69c4282c08dbbb22b86a9247d068c48da0abaa/src/stream.rs#L380-L383)

The default std resolver, will figure out the IP address for the host name [using rust std lib](https://github.com/algesten/ureq/blob/ec69c4282c08dbbb22b86a9247d068c48da0abaa/src/resolve.rs#L14-L18).

The `SocketAddr` returned from the resolver can be a mix of ipv4 and ipv6 and ureq doesn't care.

I've made some example code of how to write a bespoke resolver in #337

**Comment by ycd** [comment]
That's awesome @algesten, thank you!
