### ISSUE TITLE
Pool stream early in do_from_read when whole response is in buffer

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#264]
In Response::do_from_read, if a response has Content-Length, and that Content-Length is less than the length of `stream.inner.buffer()`, we should read those bytes immediately into a Vec, place the Vec inside Response (as an alternative to Stream), and return the stream to the pool. That will make the stream available as soon as possible for reuse. More importantly, it means that a lot of Status errors will be poolable where they otherwise wouldn't be (because the caller returns before reading the body).

**Comment by algesten** [comment]
Yep. I'm all for it!
