### ISSUE TITLE
Managing stream state when user sets Content-Length or Transfer-Encoding

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#265]
We let users set their own Content-Length or Transfer-Encoding headers on request bodies. That overrides the default Content-Length or Transfer-Encoding we would otherwise set. This means if the user makes a mistake, our stream can become out of sync. For instance, if the user sends a Content-Length of 100 and then sends 200 bytes, the server will process a request with a 100-byte body, then attempt to process the next request - which will start with body bytes and therefore be malformed. From a user-experience perspective, this would show up as an error on the *next* request on that stream, which would be hard to debug.

Some options:

 - Detect when a sent body does not match up with the user-provided headers, and "taint" the stream so we don't reuse it. This would allow the user to send malformed requests to servers if they want to, but would avoid surprising inter-request errors.
 - Produce an error from send, send_bytes etc, if the sent body does not match the user-set length (in the case of send, we would have to error after having read some of the body).

**Comment by algesten** [comment]
> Produce an error from send, send_bytes etc, if the sent body does not match the user-set length (in the case of send, we would have to error after having read some of the body)

I favour the second version.

For send(impl Reader), we could just read enough to fulfil a potential content-length set and leave the reader after that. The reader having too few bytes should be an error though.

**Comment by algesten** [comment]
I believe this is solved in ureq 3.x
