### ISSUE TITLE
Document and handle memory exhaustion issues

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#267]
It's possible for a malicious server to send very large responses and run a ureq user out of memory. For instance, the server could send a never-ending stream of headers, or a very large body.

For the response body, we should document that into_string, etc., are subject to maliciously large payloads, and if you are making requests to untrusted servers, you should use `into_reader()` and place an appropriate limit on how much you will read. Perhaps also for into_string, we should allocate the full capacity of the string up front, based on Content-Length? That would make it much faster for a malicious response to crash a ureq process, since the attacker wouldn't have to actually send all the bytes. But it might be better than slowly using up memory and crashing later? The ideal would be if it were possible to check if there's enough memory to allocate the corresponding string, and return an error instead of crashing. But I don't know of a way to do that in Rust.

For the response headers, since we can't delegate input limits to the user, I think we should add some reasonable limits. For instance, `hyper` has a max of 100 header fields, and `curl` has a max of 100k bytes for the whole header.

**Comment by algesten** [comment]
I think we could put some reasonable default limits in. Like. No string bigger than 2GB. If the user needs to handle that, they can always go via Reader. Sadly I don't think std Rust has fine grained control over allocation for String, Vec etc. It simply panics if it can't allocate.

I think a kb limit for header fields makes more sense than a fixed number. Let's do that too!

**Comment by Shnatsel** [comment]
`surf` sets the limit to 8kb and it's a bit too aggressive (241 websites out of the top million fail with surf, meanwhile curl and Firefox work fine), but there definitely needs to be _some_ limit. I've just DoS'd `ureq` with this one-liner in Linux shell:

`( echo -e "HTTP/1.1 200 OK\r"; echo -n "Huge-header: "; yes A | tr -d '\n' ) | nc -l localhost 8080`

**Comment by jsha** [comment]
#351 addresses this for header fields, number of header fields, and size of body for `into_string()`. It documents the issue for `into_reader()`. I'm undecided yet what to do about `into_json()`. I suppose everything that parses JSON strings is subject to reading a huge string into memory? Probably we should set a size limit for the number of bytes read by `into_json()` like we will for `into_string()`. But now I'm wondering if serde_json itself should have a warning about unbounded input.

**Comment by algesten** [comment]
For `into_json()`, the same limit as for `into_string()`, 10MB should be ok.

To be nice we could provide new functions `into_string_with_limit(size: u64)` and `into_json_with_limit(size: u64)`. If we force the user to pass an argument they would have to stop and think about how much they are prepared to use.

**Comment by algesten** [comment]
I believe this is addressed, but could be further refined. Let's close for now and reopen new issues if need be.

**Comment by Shnatsel** [comment]
I can confirm that `ureq` now passes [my homebrew DoS test suite](https://github.com/Shnatsel/http-denial-of-potatoes). But it doesn't stress the more exotic parts such as chunked transfer.

**Comment by algesten** [comment]
Wihoo! We're passing the _denial-of-potatoes_ test! :D
