### ISSUE TITLE
No way to set timeout for the entire request, which allows DoS attacks

### ISSUE THREAD

**Issue by Shnatsel** [algesten/ureq#28]
ureq currently does not allow specifying a timeout for the entire request (i.e. until the request body is finished transferring), which means an established connection will keep going indefinitely if the remote host keeps replying.

This is fine for the simple use cases, like a user downloading something interactively, but enables denial-of-service attacks in automated scenarios: if the remote host keeps transferring data at a really low speed, e.g. several bytes per second, the connection will be open indefinitely. This makes it easy for an attacker who can submit URLs to the server to cause denial of service through some kind of resource exhaustion - running out of RAM, networking ports, etc.

**Comment by lolgesten** [comment]
Yes. This would be a really nice feature. I'm not entirely sure how one would implement it though. It's like the timeouts in TCP connection/read/write must be adjusted dynamically from some start time, and then top it off with closing the connection if it goes on too long.

**Comment by Shnatsel** [comment]
You could compute a request deadline (or let the user explicitly specify it, there is an opinion that [deadlines are the better API](https://www.reddit.com/r/rust/comments/8b5krv/the_case_for_deadlines/)) and then set the read timeout to `min(read_timeout, time_until_request_deadline)` every once in a while. Doing so on every read is probably wasteful, but doing no more frequently than once in e.g. 250 milliseconds should be precise enough and have a small enough performance hit.

**Comment by Shnatsel** [comment]
A simple implementation of a timeout for the entire request can be viewed here: https://github.com/neonmoe/minreq/commit/41ef16e33501712e64a5711a7f4bc132d9bfbe40
However, if used as-is it may have a significant performance penalty.

**Comment by Shnatsel** [comment]
Here's another way of accomplishing this: https://github.com/sbstp/attohttpc/pull/47
