### ISSUE TITLE
Visualsource Badge

### ISSUE THREAD

**Issue by ktamas77** [algesten/ureq#282]
Hello - sorry, it took a little longer, but your visualization is finally rendered.

Please feel free to add the badge to your Readme.MD if you'd like to.

[![Visual Source](https://img.shields.io/badge/visual-source-orange)](https://www.visualsource.net/repo/github.com/algesten/ureq)

Best,
-- Tamas

**Comment by algesten** [comment]
Took a little longer than what?

**Comment by ktamas77** [comment]
Normally it takes only a few minutes, but your render took longer. If you click on the badge, you can see the results.
