### ISSUE TITLE
Example shown in the readme does not work

### ISSUE THREAD

**Issue by jixunmoe** [algesten/ureq#285]
```rust
use ureq;

fn main() -> Result<(), ureq::Error> {
  let body: String = ureq::get("http://example.com")
      .set("Example-Header", "header value")
      .call()?
      .into_string()?;
  println!("{:#?}",body);
  Ok(())
}
```

Is missing a question mark after `.call()`.

**Comment by jsha** [comment]
Thanks! Fixed in #284.

**Comment by ffred** [comment]
doesn't work for me with the question mark !?
just tried again with the same  code as here and got that (rust 1.49 _ ureq 0.9.0) :
```
error[E0277]: the `?` operator can only be applied to values that implement `Try`
 --> src\main.rs:4:22
  |
4 |     let body: String = ureq::get("http://example.com")
  |  ______________________^
5 | |       .set("Example-Header", "header value")
6 | |       .call()?
  | |______________^ the `?` operator cannot be applied to type `Response`
  |
  = help: the trait `Try` is not implemented for `Response`
  = note: required by `into_result`

error: aborting due to previous error
```
working good without the '?' after call..

**Comment by jixunmoe** [comment]
> doesn't work for me with the question mark !?
> just tried again with the same code as here and got that (rust 1.49 _ ureq 0.9.0) :
> 
> ```
> error[E0277]: the `?` operator can only be applied to values that implement `Try`
>  --> src\main.rs:4:22
>   |
> 4 |     let body: String = ureq::get("http://example.com")
>   |  ______________________^
> 5 | |       .set("Example-Header", "header value")
> 6 | |       .call()?
>   | |______________^ the `?` operator cannot be applied to type `Response`
>   |
>   = help: the trait `Try` is not implemented for `Response`
>   = note: required by `into_result`
> 
> error: aborting due to previous error
> ```
> 
> working good without the '?' after call..

I believe the main branch is v2.x.

**Comment by ffred** [comment]
oh... I see. don't know where I get the 0.9.0 I set in cargo.toml. probably looked at several pages at the same time on crates.io and mixed things..!? don't understand... sorry. it's ok if I set it to 2.0.0.
thanks..

**Comment by jsha** [comment]
Thanks for the assist, @jixunmoe! You are correct.
