### ISSUE TITLE
ureq::Transport should impl Error

### ISSUE THREAD

**Issue by Nemo157** [algesten/ureq#294]
I am transforming responses into my own internal `api::Error` type where I expect any failed response to come back with a deserializable error. That means of the two `ureq::Error` variants `ureq::Error::Status` is always converted into my own error type, while `ureq::Error::Transport` are bubbled up as-is. Because `ureq::Transport: !Error` I have to rewrap it into a `ureq::Error` enum to be able to use it as my error source, with `impl Error for ureq::Transport` then I would be able to just store it directly into my error variants.

```rust
#[derive(Debug, thiserror::Error)]
crate enum Error {
    #[error("API response {code}, {msg}")]
    Api { msg: String, code: u16 },

    #[error(transparent)]
    // This is actually ureq::Transport, but that's !Error
    UreqTransport(#[from] ureq::Error),

    ...
}

impl ApiResponseExt for Result<ureq::Response, ureq::Error> {
    #[fehler::throws(crate::api::Error)]
    fn check_error(self) -> ureq::Response {
        match self {
            Ok(response) => response,
            Err(ureq::Error::Status(code, response)) => {
                let ErrorResponse { message: msg, .. } = response.into_json()?;
                fehler::throw!(crate::api::Error::Api { msg, code });
            }
            Err(ureq::Error::Transport(transport)) => {
                fehler::throw!(ureq::Error::Transport(transport))
            }
        }
    }
}
```

**Comment by jsha** [comment]
Yep, agreed we should do this.

**Comment by algesten** [comment]
PR done. Will put into 2.0.1
