### ISSUE TITLE
Where did the status_line go?

### ISSUE THREAD

**Issue by doivosevic** [algesten/ureq#295]
I'm having trouble finding how to get same behaviour as before with response.status_line. How is this done in 2.0?

**Comment by jsha** [comment]
The information contained in the status line is present in the three methods that access various fields from tit:

https://docs.rs/ureq/2.0.0/ureq/struct.Response.html#method.http_version
https://docs.rs/ureq/2.0.0/ureq/struct.Response.html#method.status
https://docs.rs/ureq/2.0.0/ureq/struct.Response.html#method.status_text

So if you need to reconstruct the original status line, you could do, e.g. `format!("{} {} {}", r.http_version(), r.status(), r.status_text())`. Out of curiosity, what are you using the `status_line` for?

**Comment by Kungitoo** [comment]
I used it a lot while debugging because of the nice verbosity

**Comment by algesten** [comment]
I don't think we will bring this back. Reopen a new issue if that's a problem.
