### ISSUE TITLE
Access all response headers

### ISSUE THREAD

**Issue by tazjin** [algesten/ureq#3]
Hey!

It seems as if the only way to access response headers right now is explicitly by header name. There are some cases where I'd like to iterate over all existing headers.

Maybe I've missed something, but otherwise it would be nice if there was an accessor for the `headers` field.

Cheers!

**Comment by algesten** [comment]
Fixed in 0.9.0

**Comment by tazjin** [comment]
Awesome! Thanks :)

**Comment by waldyrious** [comment]
> Fixed in 0.9.0

For future reference, that was done in 141668acb
