### ISSUE TITLE
Configure the user-agent via Agent

### ISSUE THREAD

**Issue by dimo414** [algesten/ureq#308]
Looking at [`unit.rs`](https://github.com/algesten/ureq/blob/06abdff/src/unit.rs#L381) it seems the intended way to override the user-agent is by setting the header manually on each request (e.g. `.set("User-Agent", "foo-bar")`). This get's a bit tedious if you're sending multiple requests since you need to set the same user-agent string over and over.

It'd be great if `AgentBuilder` had a `user_agent()` method that set the user-agent for all requests from that agent. Would you be open to a PR adding something like this?

**Comment by jsha** [comment]
I like that idea. We originally had setting of arbitrary headers on `Agent`, but concluded it was often unsafe - for instance it's tempting to set an `Authorization` header on an Agent that's used for a single, authenticated API. But if you later reuse that Agent for a different host you can leak tokens.

**Comment by algesten** [comment]
Yeah. I'm open to a PR with a specific `.user_agent()` call on builder.
