### ISSUE TITLE
"Bad Status: Wrong number of tokens in status line" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [algesten/ureq#316]
On some websites, e.g. http://hack.pl, ureq fails with the following error: 

> Bad Status: Wrong number of tokens in status line

However, curl and Firefox work fine.

There's 296 such websites in the top million (I'm using [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L)).

Archive with all occurrences: [ureq-bad-status.tar.gz](https://github.com/algesten/ureq/files/5978826/ureq-bad-status.tar.gz)

Code used for testing: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/ureq-smoke-test/src/main.rs

**Comment by jsha** [comment]
Thanks for the report. We recently added some stricter parsing of the status line. Per spec, [reason-phrase can be empty](https://tools.ietf.org/html/rfc7230#section-3.1.2), but the space after the status code is mandatory. hack.pl omits the space. Still, perhaps this is a place to be a little lenient and allow an omitted space.

```
00000000: 4854 5450 2f31 2e31 2033 3032 0d0a 4461  HTTP/1.1 302..Da
00000010: 7465 3a20 4d6f 6e2c 2031 3520 4665 6220  te: Mon, 15 Feb 
00000020: 3230 3231 2030 303a 3331 3a33 3120 474d  2021 00:31:31 GM
00000030: 540d 0a43 6f6e 7465 6e74 2d54 7970 653a  T..Content-Type:
```

**Comment by algesten** [comment]
I agree we can be more lenient here. I've opened a PR to that effect.
