### ISSUE TITLE
"Header field didn't end with \r" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [algesten/ureq#321]
On some websites, e.g. etihad.com, ureq fails with the following error:

> Header field didn't end with \r

Firefox and curl work fine.

There's 295 such websites in the top million (I'm using [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L)).

Archive with all occurrences: [ureq-header-did-not-end-well.tar.gz](https://github.com/algesten/ureq/files/5983467/ureq-header-did-not-end-well.tar.gz)

Code used for testing: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/ureq-smoke-test/src/main.rs

**Comment by Shnatsel** [comment]
Sorry, Github has rather annoying keyboard shortcuts; I'll fill in issue description shortly.

**Comment by jsha** [comment]
This is per spec: https://tools.ietf.org/html/rfc7230#section-3.1.2

>    The first line of a response message is the status-line, consisting
>    of the protocol version, a space (SP), the status code, another
>    space, a possibly empty textual phrase describing the status code,
>    and ending with CRLF.
>
>     status-line = HTTP-version SP status-code SP reason-phrase CRLF

Spot-checking `GET http://etihad.com/`, the status line ends in LF, not CRLF.

**Comment by nico-abram** [comment]
From [this stackoverflow answer](https://stackoverflow.com/questions/5757290/http-header-line-break-style), [section 3.5](https://tools.ietf.org/html/rfc7230#section-3.5) states:

> Although the line terminator for the start-line and header fields is the sequence CRLF, a recipient MAY recognize a single LF as a line terminator and ignore any preceding CR.

And [rfc 2616 19.3](https://tools.ietf.org/html/rfc2616#section-19.3) : 
> The line terminator for message-header fields is the sequence CRLF. However, we recommend that applications, when parsing such headers, recognize a single LF as a line terminator and ignore the leading CR.

So accepting LF instead of CRLF would not only be valid, it is recommended (But not accepting it is still compliant AIUI)

**Comment by nico-abram** [comment]
Opened https://github.com/algesten/ureq/pull/324 to try to fix this, if it is decided to accept LF line terminators for headers
