### ISSUE TITLE
Can't connect to websites that redirect to an IP address (InvalidDNSNameError)

### ISSUE THREAD

**Issue by Shnatsel** [algesten/ureq#323]
ureq fails to connect to the server if it was originally querying a domain name, but the remote host replies with a redirect to an IP address. `InvalidDNSNameError` is returned in this case.

There are 44 occurrences of this in the top 1 million websites (I'm using [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L)).

All occurrences (73 files total, but only 44 don't fail in libcurl): [ureq-invalid-dns-name.tar.gz](https://github.com/algesten/ureq/files/5983691/ureq-invalid-dns-name.tar.gz)

Code used for testing: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/ureq-smoke-test/src/main.rs

**Comment by Shnatsel** [comment]
And I think that's it for errors. I'm attaching the test tool output for all failures for reference, as well as a list of websites that successfully downloaded with libcurl but failed with ureq:  
[ureq-all-failures.tar.gz](https://github.com/algesten/ureq/files/5983755/ureq-all-failures.tar.gz)

**Comment by jsha** [comment]
This is working as expected: rustls / webpki don't support IP address certificates yet, so a redirect to any `https://<IP>` is going to fail until / unless we [add native-tls support](https://github.com/algesten/ureq/issues/319) or rustls / webpki add IP address certificate support (which is underway).

**Comment by 12932** [comment]
For anyone else who stumbles across this, ureq now supports native-tls which does support connecting to IP addresses securely, it's behind the feature flag "native-tls"
