### ISSUE TITLE
Question/Suggestion about Response documentation

### ISSUE THREAD

**Issue by ragnese** [algesten/ureq#326]
The docs say the following:

> Note that the socket connection is open and the body not read until one of into_reader(), into_json(), or into_string() consumes the response.

I assume and believe it should clarify that the socket connection is closed if/when Response is *dropped* as well, right?

**Comment by jsha** [comment]
The socket is closed if the Response is dropped _while there are unread bytes on the socket_. However, if the Response is dropped after all bytes have been read, the socket will be returned to the pool.

**Comment by algesten** [comment]
I added a paragraph about this. @jsha @ragnese does it explain the situation?

**Comment by ragnese** [comment]
Thank you @algesten. I think that's much more clear.

Out of curiosity, if you don't plan on actually using the response body, is it still advisable to consume it so that the socket can be reused? Or is it very cheap to create new sockets in the pool?

**Comment by jsha** [comment]
It's advisable to consume it so the socket can reused. Creating new sockets is somewhat expensive - it takes a couple of network round trips and a little bit of CPU to validate the certificate and do the handshaking.
