### ISSUE TITLE
stream did not contain valid UTF-8 on fastcompany URL

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#341]
In https://github.com/algesten/ureq/issues/320#issuecomment-795423427, @kl reports:
> I'm running in to this as well with this: https://www.fastcompany.com/90601037/american-surviellance-state-facial-recognition-hypocrisy

> I have the following:
>
```
let agent = AgentBuilder::new().timeout(Duration::from_secs(20)).build();
let resp = agent.get(link).call().context("failed to get article")?;
let doc = Document::from_read(resp.into_reader())?;
```

> but the result from call() is Err so I'm getting this error:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Transport(Transport { kind: Io, message: None, url: Some(Url { scheme: "https", username: "", password: None, host: Some(Domain("www.fastcompany.com")), port: None, path: "/90601037/american-surviellance-state-facial-recognition-hypocrisy", query: None, fragment: None }), source: Some(Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }), response: None })', src/resolve.rs:47:39

> So this is on the line before resp.into_reader().

@kl, I tried to reproduce this with cureq (https://github.com/algesten/ureq/blob/main/examples/cureq/main.rs), with this command line:

    cargo build --example cureq --features="charset cookies socks-proxy"
    ./target/debug/examples/cureq https://www.fastcompany.com/90601037/american-surviellance-state-facial-recognition-hypocrisy

But it succeeded for me. Can you tell me what version of ureq you're on, and if it's not the latest, can you try upgrading?

Also, I'm not able to try your example code because I don't have the `Document` struct. Would you mind sharing a full self-contained example? Thanks!

**Comment by kl** [comment]
Sure, here's a minimal example.

`main.rs`:

```rust
use ureq::AgentBuilder;
use std::time::Duration;

fn main() {
    let agent = AgentBuilder::new().timeout(Duration::from_secs(20)).build();
    agent.get("https://www.fastcompany.com/90601037/american-surviellance-state-facial-recognition-hypocrisy").call().unwrap();
}
```
`Cargo.toml`:
```
[package]
name = "ureq_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.0"
```

output:
```
Running `target/debug/ureq_test`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Transport(Transport { kind: Io, message: None, url: Some(Url { scheme: "https", username: "", password: None, host: Some(Domain("www.fastcompany.com")), port: None, path: "/90601037/american-surviellance-state-facial-recognition-hypocrisy", query: None, fragment: None }), source: Some(Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }), response: None })', src/main.rs:8:119
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I can download the file just fine with wget and Firefox.

**Comment by algesten** [comment]
[ureq_test.zip](https://github.com/algesten/ureq/files/6136705/ureq_test.zip)

Very strange. I attach my test code made from your example, and that works for me.

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/ureq_test`
$
```

**Comment by algesten** [comment]
@kl could you try use a git version from the main branch?

The reason is that we landed this https://github.com/algesten/ureq/commit/566295bebbe0261802c59ac0201a130b00344f05 which would give some more context in the error message you see.

```
ureq = { git = "https://github.com/algesten/ureq", rev="239ba342a23100ba98e03e40411ad6666a5a4225" }
```

**Comment by kl** [comment]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Transport(Transport { kind: Io, message: None, url: Some(Url { scheme: "https", username: "", password: None, host: Some(Domain("www.fastcompany.com")), port: None, path: "/90601037/american-surviellance-state-facial-recognition-hypocrisy", query: None, fragment: None }), source: Some(Custom { kind: InvalidData, error: Transport(Transport { kind: Io, message: Some("Invalid data in a header"), url: None, source: Some(Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }), response: None }) }), response: None })', src/main.rs:8:119
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I figured out what it is after inspecting the response headers. Turns out I get a `set-cookie: geodata` header back with my location in it that has an `ö` character in it that is encoded in ISO-8859-1 I think (hex F6) and this isn't valid UTF-8 so it fails on that.

**Comment by algesten** [comment]
@kl ah. so this is your ISP doing a man in the middle attack?

**Comment by kl** [comment]
No, it's fastcompany that responds with the header. I assume they do some geolocation lookup on the request IP. Try putting https://www.fastcompany.com/90601037/american-surviellance-state-facial-recognition-hypocrisy in https://websniffer.cc/ and you'll see that there is a geodata Set-Cookie header.

**Comment by algesten** [comment]
Ah. That makes sense. @jsha did some stats on how common this was in the other thread, but he was doing it from a US IP, so he might not have got the entire picture of what it's like.

Maybe I do need to tackle this 🤔

**Comment by algesten** [comment]
@kl would you mind testing the commit in #347? It should resolve the problem for you. [https://github.com/algesten/ureq/pull/347/commits/e6b48deb3bda5c7ef97d56b5db2040091c0a9653]
