### ISSUE TITLE
[Question] Is it possible to make some types UnwindSafe?

### ISSUE THREAD

**Issue by Diegovsky** [algesten/ureq#366]
Hello, I'm developing an HTTPS library for Java written in Rust and as such, a lot of native functions (as Java calls them) need to catch panics in order to avoid undefined behaviour and to translate them into exceptions. One of the things that breaks this workflow is `dyn` traits (which need to also be `UnwindSafe`) and explicitly `!UnwindSafe` types (like `UnsafeCell`). Currently, I'm using blocking `reqwest` and due to it's `blocking async` nature, it's quite bloated for my purpose and most types are not `UnwindSafe` because of all the async stuff. I would love to use `ureq` because of it's simplicity and straight to the point mindset, but most types are also `!UnwindSafe`, particularly the `Response` type.

Of course, this isn't a problem to 99,99% of the users and I'm aware of it. Even so, I believe this may be a simple change to be made. I did a light search on the `Response` struct and it seems largely made of boxed `dyn` traits. The solution might be simple: adding a `RewindSafe` bound to those boxed traits. Since this adds constraints on traits, it also adds a bit of complexity to the code. Does anyone know if this is actually a big change and breaks stuff?

**Comment by algesten** [comment]
Hi! Thanks for trying ureq for this!

The answer to your question is "try and see". I don't know enough about `UnwindSafe` to know the implications of adding that trait bound to our `dyn`. 

Adding it will be backwards compatible, so I can't see any versioning problems doing it.

I suspect however there will be _some_ third party crate where you find some type that won't fit, and it'd be interesting to see where that is (like rustls or similar).

**Comment by Diegovsky** [comment]
Thanks for the quick response! It's good to know it is possible. Since you liked the idea, I'll try to make those changes as soon as I have time and report back.

**Comment by Diegovsky** [comment]
I did some changes and it is indeed as you said. With TLS feature on, it stops being `UnwindSafe`. Thanks for your input and patience, though!

**Comment by algesten** [comment]
Good to know. Thanks!
