### ISSUE TITLE
Provide a way to instantiate `ureq::Error::Transport` for tests

### ISSUE THREAD

**Issue by tgeoghegan** [algesten/ureq#373]
I have some retry logic that retries requests on certain HTTP status codes and on `ureq::Error::Transport`. I want to test my logic that determines if an error is retryable by feeding it synthetic `ureq::Error` values. I can easily create an instance of `ureq::Error::Status` since `ureq::Response::new` is public ([as noted in the doccomment](https://docs.rs/ureq/2.1.0/ureq/struct.Response.html#method.new), it is indeed useful for unit tests), but there's no way for a client to create a `ureq::Error::Transport` value.

**Comment by algesten** [comment]
Can you make an `std::io::Error` and use convert that with `.into()`?

**Comment by tgeoghegan** [comment]
It looks like that would let me construct the `Transport` variant of `ureq::Error`, which I think might suffice for the testing case I described. I'm afraid I've since deleted the tests in question, so I don't really remember.

**Comment by algesten** [comment]
Thanks!
