### ISSUE TITLE
HandshakeFailure connecting to HTTPS site

### ISSUE THREAD

**Issue by tpoliaw** [algesten/ureq#381]
I am trying to make a get request to an HTTPS site. 
My request looks like this
```rust
ureq::get("https://example.com/endpoint").call()?;
```
and it's giving me `received fatal error: HandshakeFailure`. The same request via curl/reqwest/Python's requests returns successfully but I was hoping to use `ureq` for its minimal footprint. Is there any way I can get any more information out of the error to trace what is going on? Getting the error and printing via debug doesn't give much more but I can include it if it would be useful.

It is a private/internally hosted site but is accessible externally and shouldn't need any proxies or authentication. I could believe there's an odd configuration some where on the server side but I'm not sure where to start looking. From another issue on here about handshake errors suggested version incompatibilities. If that is any help, querying the server gives

```
❯ nmap -sV --script ssl-enum-ciphers -p 443 [IP REDACTED]

Starting Nmap 6.40 ( http://nmap.org ) at 2021-04-28 13:01 BST
Nmap scan report for host.example.com (xxx.xxx.xxx.xxx)
Host is up (0.00030s latency).
PORT    STATE SERVICE  VERSION
443/tcp open  ssl/http Apache httpd 2.4.6 ((Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips)
| ssl-enum-ciphers: 
|   SSLv3: No supported ciphers found
|   TLSv1.0: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|     compressors: 
|       NULL
|   TLSv1.1: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|     compressors: 
|       NULL
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA256 - strong
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|     compressors: 
|       NULL
|_  least strength: strong
```
I have tried with and without `rustls-native-certs` feature.

Any help getting this running would be appreciated. Thanks

**Comment by jsha** [comment]
Hi @tpoliaw! Thanks for the report. That nmap is indeed helpful. [rustls](https://docs.rs/rustls/0.19.1/rustls/) only supports TLS 1.2 and TLS 1.3. Within those TLS versions, it only supports ciphersuites that it considers to provide a "good" level of cryptographic security. [You can see the list here](https://docs.rs/rustls/0.19.1/src/rustls/suites.rs.html#443-455). In particular, for TLS 1.2:

```
    &TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
    &TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
    &TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
    &TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
    &TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
    &TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
```

Which shares no overlap with your server. In particular, your server offers no GCM or Poly1305 ciphersuites. It sound like you're able to update the server's configuration. I recommend [Mozilla's SSL Configuration Generator](https://ssl-config.mozilla.org/) for instructions on how to configure it.

**Comment by tpoliaw** [comment]
Ok. Thanks for the explanation and the links to the rustls source. I'm not in a position to update the servers but I'll try and suggest it to people who are. I'll use `reqwest` for now and then come back to ureq if/when I can.

**Comment by jsha** [comment]
We also have an open issue to support native-tls, which I think we will do when we find some time: #319. That would allow connecting to servers that don't support any of the rustls-supported ciphersuites.
