### ISSUE TITLE
Incomplete documentation (version: 2.1.1) on `doc.rs`

### ISSUE THREAD

**Issue by kondongx** [algesten/ureq#383]
# Incomplete documentation (version: 2.1.1) on `doc.rs`

<img src = "https://user-images.githubusercontent.com/28899471/116967748-9d364580-ace5-11eb-9a93-b128ff4b0361.png" height="80%" width="80%">

Besides document version 2.1.0 doesn't have this problem:
<img src = "https://user-images.githubusercontent.com/28899471/116967827-c951c680-ace5-11eb-9273-c996f135ac60.png" height="80%" width="80%">

**Comment by cbioley** [comment]
@kondongx Shouldn't you just click on the little `+` next to `impl Agent`?

**Comment by kondongx** [comment]
You are right🤦🏽
