### ISSUE TITLE
Custom SSL certificate

### ISSUE THREAD

**Issue by LukeMauldin** [algesten/ureq#386]
I am looking at using ureq 2.X on x64 Linux and Windows.  How do I add in custom SSL certificates for ureq?
I have the custom SSL certificates added into the system stores on both Linux and Windows and curl, which uses openssl, loads the certificates correctly.  However, from reading the documentation of ureq, it does not use openssl so what steps do I need to take to add in the certificates?

**Comment by jsha** [comment]
You'll need to add dependencies on [rustls](https://docs.rs/rustls/0.19.1/rustls/) and [rustls-native-certs](https://docs.rs/rustls-native-certs/0.5.0/rustls_native_certs/) (with the "rustls" feature). Call [load_native_certs](https://docs.rs/rustls-native-certs/0.5.0/rustls_native_certs/fn.load_native_certs.html) to get a `RootCertStore`, then create a [ClientConfig](https://docs.rs/rustls/0.19.1/rustls/struct.ClientConfig.html) with that RootCertStore.

Then, build a `ureq` agent with the [tls_config](https://docs.rs/ureq/2.1.1/ureq/struct.AgentBuilder.html#method.tls_config) set to that RootCertStore.

Phew, we should document all this! :-)

**Comment by LukeMauldin** [comment]
Thanks for the information and yes some documentation or an example would be very nice.

**Comment by LukeMauldin** [comment]
I followed the information about and rustls reads the Linux system certificates and works as expected. However, on windows it does not read the computer trust certificates and fails https with unknown issuer. Are there any special steps for windows?

**Comment by jsha** [comment]
No special steps on Windows as far as I know - rustls-native-certs should load from the platform certificate store. It's been a while since I added a custom root on Windows, so there might be some subtleties I'm forgetting - maybe you added the root just for one user or one context? Does the added root work with other software, e.g. OpenSSL?

**Comment by LukeMauldin** [comment]
I added the root certificate on windows at the computer level. Normal windows programs such as MSEdge use it, along with c++ programs using the native windows WinHttp apis, and Golang programs work too with the custom certificate.
OpenSSL does not work by default with the certificate because OpenSSL reads from its own certificate store on windows and not the windows computer certificate store.

**Comment by LukeMauldin** [comment]
When using windows development environment with rls and navigating to definition, it looks like rustls-native-certs on windows it loading in unix.rs instead of windows.rs. Although maybe that is an rls issue?

**Comment by jsha** [comment]
hm, that seems like a potential issue. Are you using WSL? I'm not sure under what environments Rust / rustls-native-certs will build for Windows vs unix.

**Comment by LukeMauldin** [comment]
I am not using WSL. I am running on Windows Server 2019 and rust 1.52.1 MSVC.
How can I temporarily disable certificate validation on Windows for now while this issue is being looked at?

**Comment by jsha** [comment]
That's in rustls' [DangerousClientConfig](https://docs.rs/rustls/0.19.1/rustls/struct.DangerousClientConfig.html), specifically `set_certificate_verifier`.

**Comment by LukeMauldin** [comment]
I set the config option you specified and that allowed me to work around the problem on windows. However, moving forward, how do we get the underlying bug addressed on windows? Should I open an issue on rustls?

**Comment by LukeMauldin** [comment]
I think I figured out some more on the issue. rustls-native-cers in windows.rs only adds certs from the current user, whereas my custom certificate is stored in the local computer level.

**Comment by LukeMauldin** [comment]
Created issue https://github.com/ctz/rustls-native-certs/issues/22 to track underlying bug.

**Comment by jsha** [comment]
Thanks for digging into this! I think from the ureq side this is done. Feel free to reopen.

**Comment by schneems** [comment]
I've got a tangential question: Do you have any suggestions for unit (or integration testing) that this was set up correctly? Is there anything like MITM proxy wrapper for rust libraries that could simulate a restricted network and some way to load test certs without requiring that they're instaled into the host machine?

I understand this isn't a `ureq` specific question, just posting here in case anyone has suggestions.
