### ISSUE TITLE
use no_delay on the TcpStream

### ISSUE THREAD

**Issue by whyCPPgofast** [algesten/ureq#390]
Hi,

https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_nodelay

This is basically a default for most modern http clients since it reduces latency of sending bytes.

I was going through the stream.rs file but I'm not sure how to implement it and make a pull request so I decided to open this issue sorry about that.

**Comment by jsha** [comment]
Some references:

[curl sets nodelay by default](https://curl.se/libcurl/c/CURLOPT_TCP_NODELAY.html)
[reqwest sets nodelay by default](https://docs.rs/reqwest/0.11.3/reqwest/struct.ClientBuilder.html#method.tcp_nodelay)
[Go sets nodelay by default on all TCP connectiosn](https://golang.org/pkg/net/#TCPConn.SetNoDelay)

I'm in favor of implementing. Let's build it on top of #389

**Comment by algesten** [comment]
Hi! Thanks for this PR – looks great. 

I guess it's somewhat dodgy to change the default value, but I can't see how it would break any existing code and we have precedence in all other http libraries. 

Let's merge!

Thanks!
