### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by mleonhard** [algesten/ureq#392]
I wish to use ureq to call Twilio's API which [uses HTTP authentication](https://www.twilio.com/docs/usage/security).  Let's add some methods to support this:

```rust
impl Response {
    pub fn set_digest_auth(self, username: impl AsRef<str>, password: impl AsRef<str>) -> Self {}
    pub fn set_basic_auth(self, username: impl AsRef<str>, password: impl AsRef<str>) -> Self {}
}
```

Alternatively, we could add something to the docs explaining another way to do it.

**Comment by mleonhard** [comment]
A workaround is to include the password in the Url:
```rust
let mut url = Url::parse("https://lookups.twilio.com/v1/PhoneNumbers?Type=carrier").unwrap();
url.path_segments_mut()
    .unwrap()
    .push(&tel.inner().to_string());
url.set_username(&twilio_sid).unwrap();
url.set_password(Some(&.twilio_token)).unwrap();
let response = ureq::request_url("GET", &url).call().unwrap();
if response.status() == 404 {
    return None;
}
...
```

Unfortunately, ureq logs url which now includes the password:
```
INFO sending request GET https://username:----PASSWORD----@lookups.twilio.com/v1/PhoneNumbers/10001112222
```
See "Redact password in logs" https://github.com/servo/rust-url/issues/714 .

**Comment by fkusche** [comment]
You can do it by adding the authentication header manually
```rust
fn get_basic_auth_header( user: &str, pass: &str ) -> String {
    let usrpw = String::from( user ) + ":" + pass;
    String::from( "Basic " ) + &base64::encode( usrpw.as_bytes())
}
```

And then
```rust
let resp: SendResponse = ureq::post( &url )
    .set("Accept", "application/json")
    .set("Authorization", &get_basic_auth_header(&cfg.token_id, &cfg.token))
    ...
```

**Comment by strohel** [comment]
HTTP basic auth is as easy as adding a correctly formatted header, though adding a helper to create such a header would be convenient.

HTTP digest auth is slightly more involved as it requires a round-trip to the server and adapting the second query to the nonce in server's first response.

I see ureq has had some support for HTTP authentication in the past, but it has been removed:
https://github.com/algesten/ureq/blob/3b68dce23a67ffbf887e2109e9a6c41e17803d07/CHANGELOG.md?plain=1#L75-L76

@algesten would such a feature fit into ureq (would a PR adding that be welcome)?

**Comment by algesten** [comment]
@strohel I think we should wait for 2.4.0 release (any day now). The middleware PR that just landed #448 might be a pretty good alternative for elaborate auth schemes (OAuth2 or even Digest).

We could consider providing default middleware for stuff like Digest.

**Comment by mleonhard** [comment]
This is closed as "completed" but I can't find anything about it in the ureq docs.  Shall we re-open?

https://docs.rs/ureq/2.12.1/ureq/struct.Request.html

**Comment by algesten** [comment]
@mleonhard I cleaned up/closed out a few of the issues in preparing for ureq 3.x ([any day now](https://github.com/algesten/ureq/issues/920)).

* Convenience method for basic auth
* Convenience method for digest auth

ureq 3.x is based on the http crate, meaning we don't have our own URI implementation anymore. We should however support BASIC auth when the username/password is provided in the URI. The URI is [not logged in clear text anymore](https://github.com/algesten/ureq/blob/main/src/util.rs#L230). The idea is that DEBUG is safe. TRACE shows (potentially sensitive) details on protocol level.

Having looked around the code. I think we're missing encoding the BASIC auth from the URI. This should be raised as a new issue.

The DIGEST method can be implemented [as middleware](https://docs.rs/ureq/3.0.0-rc4/ureq/middleware/trait.Middleware.html). I personally never encountered a service using it, and my starting point is that I think this middleware could live in a separate crate.

**Comment by strohel** [comment]
https://github.com/algesten/ureq/pull/1075 has been submitted which would add HTTP Digest auth as a middleware.
