### ISSUE TITLE
Error setting many headers independently or in a loop

### ISSUE THREAD

**Issue by miconda** [algesten/ureq#396]
Hello,

it's my first time playing a little bit more with Rust and I am trying to expose a few wrapper functions to C via a shared library. I hope I haven't missed anything obvious but it seems that headers cannot be set independently many times or in a loop.

I tried to do:

```
162:    let req = agent.get(r_url_str);
163:
164:    req.set("X-My-Header", "Secret");
165:    req.set("X-My-Header2", "Secret2");
```

And I get:

```
use of moved value: `req`

value used here after moverustc(E0382)
ruxc.rs(162, 9): move occurs because `req` has type `ureq::Request`, which does not implement the `Copy` trait
ruxc.rs(164, 9): `req` moved due to this method call
ruxc.rs(165, 5): value used here after move
```

I tried to use reference for `req`, but the result is the same. Same result when using a `for` loop to add many headers.

Again, might be my lack of proper Rust knowledge, sorry if that's the case here. But maybe the `ureq` is not supporting it right now, knowing that will save time digging in more. Any hints are appreciated, thanks!

**Comment by miconda** [comment]
Following up, as I looked at the code of `ureq::Request`, I discovered the function `set()` returns `self` by value, changed to:

```
162:    let mut req = agent.get(r_url_str);
163:
164:    req = req.set("X-My-Header", "Secret");
165:    req = req.set("X-My-Header2", "Secret2");
```

and the error is gone.

This could be the recommended way in Rust because it seems to prefer copy by value with the variables/parameters, but might be useful to add a new function to push headers, given that headers are kept in a vector.

Closing, current solution is enough for me.

**Comment by algesten** [comment]
@miconda Ah yes.

This is because the ureq request follows the [consuming builder pattern](https://doc.rust-lang.org/1.0.0/style/ownership/builders.html#consuming-builders:)

The idea is that you typically do a chain involving the last call (send body etc) like this:

```rust

let response = agent.get(url)
   .set("x-my-header1", "secret")
   .set("x-my-header2", "secret2")
   .call()?;
```

**Comment by miconda** [comment]
@algesten: makes sense -- coming from C, I am used with a different approach. Thanks!
