### ISSUE TITLE
Doesn't work with some websites?

### ISSUE THREAD

**Issue by mcseemk** [algesten/ureq#4]
Hi! Seems like ureq is not compatible with some websites. Any idea why?
Here is an example:

    let resp = ureq::get("https://www.okex.com/api/spot/v3/products")
        .set("Connection", "keep-alive")
        .set("Accept-Encoding", "identity")
        .timeout_connect(5_000)
        .timeout_read(5_000)
        .timeout_write(5_000)
        .call();
    if !resp.ok() {
        eprintln!("Error! Code {}, line {}", resp.status(), resp.status_line());
    }

It prints: Error! Code 500, line HTTP/1.1 500 Bad Status

Same URL works fine via firefox/chrome/curl/hyper/mio_httpc.

Same thing happens for URL https://api.fcoin.com/v2/public/symbols

**Comment by lolgesten** [comment]
Thanks! I'll look into it!

**Comment by algesten** [comment]
This was because these sites don't return a status text which the lib expected. Fixed in 0.9.1
