### ISSUE TITLE
How to inspect a ureq::Error::Transport?

### ISSUE THREAD

**Issue by couchand** [algesten/ureq#400]
The `ureq::Error` enum allows me to pattern-match to distinguish between HTTP errors and a whole host of network errors.  In the case of HTTP errors, I can further inspect the `ureq::Response` to gain useful insight on the nature of the error.

However, the `ureq::Transport` struct is woefully featureless.  It has no accessor methods, and practically only implements `Display`.  I can turn it back into a `ureq::Error` and call `.kind()` on it, which provides a high-level categorization, but for any more details I have to rely on a stringly-typed description.

Should `ureq::Transport` have accessors for `message` and `source`?  Should I just inspect the `ErrorKind` and not try to use the rest?  Should I perform string manipulation on the result of the `Display` impl?

---

To provide brief context on my use-case: I want to log errors with as much detail as possible without ever logging the raw URL, as it includes sensitive user data.  What should I log?

**Comment by algesten** [comment]
Hi! Thank you for trying out ureq.

The kind of inspection you're after is intended to be done on the `ureq::Error` level. On that level you have `kind()`, `src()` etc.

I think the best way to do the logging you want is to start with `ErrorKind` and then only dig into `Response` if you detect an HTTP error.

I could be persuaded to provide `kind()` and `src()` on the `Transport` level too, but would be interested to first discuss the relative merits of doing so, rather than just use what's there already.

**Comment by couchand** [comment]
That sounds reasonable enough.  I'm not sure the methods *need* to be on `Transport`, but for my part I'd prefer them to be there, since I can only really see wanting to call them on a `Transport`.  I tend to use `or_any_status` liberally, since I don't like to mix up errors from different layers myself.

The one other specific ask I'd have is an accessor for the `message`, as there does not seem to be any way to get at that without going to the `Display` impl.

As a general matter, I wish it was easier to tell from the API and/or documentation what information would be relevant for the various possible errors.  When is `source` populated?  Is `message` distinct from the `Display` of `ErrorKind`?  If so, in what cases will it have additional details?  etc. etc.

**Comment by algesten** [comment]
Today I had a bit of time to look into this closer, and I agree we should make it easier to inspect the error. PR provided.
