### ISSUE TITLE
setting redirects in the Request struct

### ISSUE THREAD

**Issue by ayrat555** [algesten/ureq#404]
I think `redirects` field was removed in this pr https://github.com/algesten/ureq/issues/174#issuecomment-714199913

But it would be nice to be able to set it in the Request struct if you don't want to use Agent

**Comment by algesten** [comment]
Hi! Welcome to ureq!

The problem with having redirect straight on request is that although convenient for quick usage, it conceptually breaks what's going on. 

If we consider `Request` being "one http request", then a redirect is a second http request following a `location` header. It becomes a bit strange that `Request` would map to more than one actual http request.

**Comment by ayrat555** [comment]
so I should use the Agent to set the number of redirects? I think if I'm not reusing it, there is some performance overhead to instantiate it for every request?

**Comment by algesten** [comment]
whether you configure it or not, there's always an agent involved coordinating every request. 

the quick request methods instantiates an agent that is used once. 

so in some respects, you can make it more efficient by reusing the same agent for multiple requests.

**Comment by ayrat555** [comment]
if it's started anyway, why can't it be started under the hood when setting the number of redirects in Request?

**Comment by algesten** [comment]
It's not so much about _can or can't_ but rather _should or shouldn't_ due to the reasons stated in https://github.com/algesten/ureq/issues/404#issuecomment-897545282

**Comment by ayrat555** [comment]
makes sense I guess. would be nice to have a note about it the readme or docs. Because from a user perspective it's not obvious
