### ISSUE TITLE
docs.rs documentation broke with 2.1.1 release

### ISSUE THREAD

**Issue by maxbla** [algesten/ureq#411]
To be more specific, the methods are all in the sidebar, but aren't actually present on the page.
See comparison:

- [2.1.0 Agent (works)](https://docs.rs/ureq/2.1.0/ureq/struct.Agent.html)
- [2.1.1 Agent (broken)](https://docs.rs/ureq/2.1.1/ureq/struct.Agent.html)
- [2.1.0 Response (works)](https://docs.rs/ureq/2.1.0/ureq/struct.Response.html)
- [2.1.1 Response (broken)](https://docs.rs/ureq/2.1.1/ureq/struct.Response.html)

I'm not sure why this happened or how to fix it, but I thought I'd let you know.

**Comment by algesten** [comment]
Thanks!

We should have a look.

**Comment by algesten** [comment]
Is this broken for you still? I can use those links.

**Comment by algesten** [comment]
In the latest version they're back. Sadly it didn't fix 2.1.1.
