### ISSUE TITLE
Easy method for Response to get bytes

### ISSUE THREAD

**Issue by leafjolt** [algesten/ureq#417]
I'm using ureq for a new project and I was looking in the docs for the `Response` struct for a `as_bytes` method, like the one in [minreq](https://docs.rs/minreq/2.4.2/minreq/struct.Response.html#method.as_bytes), but I couldn't seem to find one. Is there an easy way to get a raw `&[u8]` from a `Response`?

**Comment by algesten** [comment]
Hi there! Welcome to ureq!

I believe what you're looking for is `into_reader()`. The example in the documentation for that function shows how to get "raw bytes" out of ureq: https://docs.rs/ureq/2.2.0/ureq/struct.Response.html#method.into_reader

**Comment by leafjolt** [comment]
This seems to work perfectly for what I need. Thank you!
