### ISSUE TITLE
Getting RelativeUrlWithoutBase parse error unexpectedly

### ISSUE THREAD

**Issue by leafjolt** [algesten/ureq#418]
I'm currently building an app that requires downloading files from certain URLs and I came into a problem with ureq's parsing of URLs for requests. An example URL that I might be downloading is the following: "https://www.dailymotion.com/cdn/H264-320x240/video/x841s1q.mp4?sec=zWY8RT1kvvBYf1HO_tPU2r6eNh9dY-U38KxOSHe5oCpCf02Um5_KgA8P6LjLYdQA". I have a method on a struct called `direct_url()` that returns a String of the link to the file I need to download. However, when I run `ureq::get(self.direct_url().as_str())`, it gives me a RelativeUrlWithoutBase error when parsing the URL. When I passed the url directly to `ureq::get` instead of calling my `direct_url` method, it worked perfectly fine. I'm wondering why I'm getting an error for one case but not for the other.

**Comment by algesten** [comment]
`RelativeUrlWithoutBase` probably means you are sending a relative url without a host. 

Example

If you shorten a URL like `https://example.com/some/special/path`

to just `/some/special/path`, I imagine you will get this error. 

Could it be that your function shortens the URL too much?

**Comment by leafjolt** [comment]
I also thought that might be the case, but when I ran `println!("{}", self.direct_url())` to test it, it printed the full absolute url out.

**Comment by leafjolt** [comment]
I have found the issue; the `direct_url()` method was returning a String that actually contained quotation marks in it. I fixed it by just replacing the quotation marks with nothing and then passing that to `ureq::get`. Thank you for your help!
