### ISSUE TITLE
Request via specified NIC

### ISSUE THREAD

**Issue by benydc** [algesten/ureq#419]
Is it possible to bind a request to a specific network interface?

**Comment by algesten** [comment]
To solve this completely, might be beyond `ureq` capabilities right now. ureq relies on Rust's `std::net` to [connect a socket to the remote host](https://doc.rust-lang.org/1.55.0/std/net/struct.TcpStream.html#method.connect).

It implicitly does a DNS lookup on `addr` (which comes from the request URL). That lookup will result in some IP address, and then it would go via the local routing table for getting to that IP. There is no direct control over which NIC is being used.

This would create an issue for multihomed computers. I.e. if the routing table is such that there are multiple ways of reaching the same IP and that (what I assume is `libc`), does not resolve primarily to the route/NIC wanted.

Another situation would be that the URL can resolve to multiple IP addresses, and it ends up using "the wrong one" (split DNS scenario or similar), but it if selected another IP it would implicitly also select the correct NIC. There is some control that can be had over DNS lookup, check out [this example](https://github.com/algesten/ureq/blob/main/examples/ipv6.rs).

**Comment by jsha** [comment]
I agree this is beyond ureq's capabilities. A sketch of how you might achieve something:

First, figure out which IP addresses are bound to which NIC. At the TCP layer we don't have the ability to say "use this NIC," but we do (in a platform-specific way) have the ability to say "use this source IP," and that _may_ amount to the ability to choose a NIC, depending on your setup.

Read this, about how to use a specific source IP: https://idea.popcount.org/2014-04-03-bind-before-connect/

You would then need to find a way of creating a TCP connection in Rust that is lower-level than net::TcpStream. On a quick Google, maybe https://github.com/libpnet/libpnet ? You'd use this method to set the source IP of a socket _before_ you dial it.

You would then need some way to package that up and hand it off to ureq. Right now that doesn't exist. I could imagine adding an integration point where the user could supply a Dialer that takes hostnames or IP addresses and produces a `Read + Write` or similar. However, this is pretty far down the line - first you would need to figure out how to dial from a specific source IP in Rust.

**Comment by benydc** [comment]
@algesten @jsha thank you!
In the end I'm going to hand roll the client, using `net2` crate with TcpBuilder, or with `libpnet` crate or whatever I can find on google. This issue can now be closed, thank you!
