### ISSUE TITLE
HTTPS proxy support

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [algesten/ureq#420]
ureq supports HTTP proxies, but not HTTPS proxies. HTTPS proxies are essentially the same thing but communicating over TLS.

For examples of other code, they are supported by reqwest and [curl](https://daniel.haxx.se/blog/2016/11/26/https-proxy-with-curl/).

**Comment by algesten** [comment]
I don't mind if someone wants to add this.

**Comment by algesten** [comment]
This is solved in ureq 3.x
