### ISSUE TITLE
Please (re-)add shortcuts for the PATCH method

### ISSUE THREAD

**Issue by homeworkprod** [algesten/ureq#429]
I was surprised to find that there is no shortcut for the `PATCH` method (RFC 5789).

After forking this repository, I discovered #211, but I'm still unable to understand from that *why* you have dropped the already existing shortcuts. It seems rather arbitrary.

I'm using `PATCH` to access parts of the Discord API (which I'd say can be considered *somewhat popular*) and also have both added as well as used it to/in other REST APIs. Given it's an Internet Standard and has it's place to complement the band of GET/POST/PUT/DELETE to transfer data in an effective way, I strongly suggest to add it back.

For the record, both surf and reqwest (other popular Rust HTTP clients) support it first-class as well (why wouldn't they).

So, pretty please, I guess? :)

PS: I made a PR for this, #430, in case you're interested.

**Comment by homeworkprod** [comment]
Closing this as #430 has been merged.

**Comment by algesten** [comment]
Thanks!

**Comment by homeworkprod** [comment]
Should this appear in the changelog?

**Comment by lolgesten** [comment]
It will do. We typically do an update to changelog eyeing through all the commits that went in. So I will put it there.
