### ISSUE TITLE
Authentication header is not preserved in Same-Host Redirects 

### ISSUE THREAD

**Issue by llde** [algesten/ureq#442]
GIthub Rest api devolve to unauthenticated access if Authentication header isn't preserved in 301 redirects.  
cUrl -L do follow the redirect preserving the header.

**Comment by lolgesten** [comment]
Hi llde! Welcome to ureq!

For posterity I'm quoting the relevant curl doc:

> -L … When authentication is used, curl only sends its credentials to the initial host. If a redirect takes curl to a different host, it won't be able to intercept the user+password. See also --location-trusted on how to change this.

> --location-trusted (HTTP) Like -L, --location, but will allow sending the name + password to all hosts that the site may redirect to.

**Comment by algesten** [comment]
Hi llde! Welcome to ureq!

For posterity I'm quoting the relevant curl doc:

> -L … When authentication is used, curl only sends its credentials to the initial host. If a redirect takes curl to a different host, it won't be able to intercept the user+password. See also --location-trusted on how to change this.

> --location-trusted (HTTP) Like -L, --location, but will allow sending the name + password to all hosts that the site may redirect to.

**Comment by algesten** [comment]
Some thoughts about this issue. Currently `ureq` has one behavior with regards to preserving auth headers on redirects. It's arguably very conservative, not preserving _any_ such header at all.

Changing that behavior to preserve headers when redirecting to the same host, is a small change, but could be argued that it breaks backwards compatibility. Furthermore, it could cause a potential security issue. Someone somewhere could rely on the current behavior?

Having said that, I'm not against making this change, however I would like to model it on how curl does it. We can think of it as being three "levels" of behavior.

* No auth headers on redirect (current behavior, no equivalent in curl)
* Auth headers when redirect to same host/port (curl `-L` behavior – TODO: investigate whether curl actually matches just host or all of scheme, host and port)
* Auth headers on all redirect (curl `--location-trusted` behavior)

I suggest these three levels of behavior would be defined in a new enum that is set on `Request`. Something like:

```rust
pub enum RedirectAuthHeaders {
  Never,
  SameHost,
  Always,
}

impl Request {
…
   pub fn set_redirect_auth_headers(self, v: RedirectAuthHeaders) { … }
}
```

The enum would default to `Never` to preserve to not break backwards compatibility.

**Comment by algesten** [comment]
@jsha would love your thoughts on this issue.

**Comment by jsha** [comment]
I think your plan of making the "headers on redirect" behavior customizable is great. I think we should make it a setting on Agent rather than Request. And I think we should make it control "sensitive" headers, not just auth. That would also include "cookie".

**Comment by llde** [comment]
I'm not sure where preserving the header only with the same host (and with the same scheme and port) would introduce a security issue (it's still internal to the host, if the host is compromised it's problematic even the first time the header is sent).
I will try to make a test for curl -L 

@jsha if I understand the code correctly, currently Cookie isn't stripped on reidrect, is that right?

**Comment by jsha** [comment]
> I'm not sure where preserving the header only with the same host (and with the same scheme and port) would introduce a security issue (it's still internal to the host, if the host is compromised it's problematic even the first time the header is sent).

I agree, it's probably not a security issue. But it is a behavior change, which arguably should be a semver major revision. Making this option a setting for now would allow us to make the more useful behavior available, while keeping the option to change the default behavior in some future semver major revision. But I could also be convinced that "keep authorization on same-origin redirects" is clearly enough the right behavior that we could make that the default now and treat it as a semver minor revision.

> @jsha if I understand the code correctly, currently Cookie isn't stripped on reidrect, is that right?

Ah, you're right. I was thinking of the "sensitive header redaction" we do for logging.

> Also maybe the Always option is the most dangerous option of all, should be putted in a "feature"?

Indeed it is dangerous, and seems like it would almost never be useful. I think we should omit the Always option, at least for now. If someone really does turn out to need it, it can be accomplished by handling redirects manually.

**Comment by llde** [comment]
I'm setting up a test rocket server to test curl behaviour.
Should we keep a sperate option for cookie and authorization headers?

**Comment by jsha** [comment]
BTW you may also be interested in some past discussion here: https://github.com/algesten/ureq/issues/152

**Comment by algesten** [comment]
> I'm not sure where preserving the header only with the same host (and with the same scheme and port) would introduce a security issue (it's still internal to the host, if the host is compromised it's problematic even the first time the header is sent). 

I'm thinking about SaaS platforms where customers have their "space" as a paths: example.com/customer1 example.com/customer2

It's a remote possibility, but still.

**Comment by llde** [comment]
If the servive do have a strong separation of components, the service should not return redirects inter spaces. Seems like a error in design to return  aredirect in this case

BTW I did test and curl doesn't do port checks. Authorization is forwarded even if the port is different. (Test wasdone with an old test server do not care about names)

 lorenzo@AveSithisPC  ~  ureq  curl 127.0.0.1:8080/redir  -H "Authorization: token etuttigliangeliincolonna" -L 
curl: request
HTTP/1.1 301 Moved Permanently
Location: http://127.0.0.1:8042/satan
Server: Rocket
Content-Length: 0
Date: Thu, 09 Dec 2021 22:10:15 GMT

HTTP/1.1 666 <unknown status code>
Content-Type: text/plain; charset=utf-8
Server: Rocket
Content-Length: 10
Date: Thu, 09 Dec 2021 22:10:15 GMT

127.0.0.1:8080 instance response
HEAD /redir:
    => Error: No matching routes for HEAD /redir.
    => Autohandling HEAD request.
    => Matched: GET /redir (redirect)
HeaderMap { headers: {Uncased { string: "Host" }: ["127.0.0.1:8080"], Uncased { string: "User-Agent" }: ["curl/7.80.0"], Uncased { string: "Accept" }: ["*/*"], Uncased { string: "Authorization" }: ["token etuttigliangeliincolonna"]} }
    => Outcome: Success
    => Response succeeded.

172.0.0.1:8042 instance response
HEAD /satan:
    => Error: No matching routes for HEAD /satan.
    => Autohandling HEAD request.
    => Matched: GET /satan (satan)
HeaderMap { headers: {Uncased { string: "Host" }: ["127.0.0.1:8042"], Uncased { string: "User-Agent" }: ["curl/7.80.0"], Uncased { string: "Accept" }: ["*/*"], Uncased { string: "Authorization" }: ["token etuttigliangeliincolonna"]} }
    => Outcome: Success
    => Response succeeded.
