### ISSUE TITLE
How to get the response status etc when using a struct 

### ISSUE THREAD

**Issue by lukehinds** [algesten/ureq#464]
Apologies if this is more of a rudimentary rust question, but wanted to see what the idiomatic ureq approach should be:

Using my code as example. I have a `GetRef` struct

```rust
#[derive(Serialize, Deserialize)]
struct GetRef {
    #[serde(rename = "ref")]
    ref_: String,
    node_id: String,
    url: String,
    object: ObjectGetRef,
}

#[derive(Serialize, Deserialize)]
struct ObjectGetRef {
    #[serde(rename = "type")]
    type_: String,
    sha: String,
    url: String,
}
```

I then use this struct for a GET request:

```rust
let resp: GetRef = ureq::get(&get_ref_url)
        .set("accept", "application/vnd.github.v3+json")
        .call()?
        .into_json()?;
```

This then allows me to access my structs elements quite nicely

```rust
println!("ref sha{:?}", resp.object.sha);
```

However, how can I now access the status code of the response (to check for 200 , 404 etc)?

**Comment by algesten** [comment]
Hi there! Welcome to `ureq`.

This part: `.into_json()?;` this part consumes the `Response` object and converts the response JSON body to the struct.

If you want the status code, you have to stop before doing the body part. Like this:

```rust
let resp: GetRef = ureq::get(&get_ref_url)
        .set("accept", "application/vnd.github.v3+json")
        .call()?;

println!("Status is: {}", resp.status());

let get_ref: GetRef = resp.into_json()?;
```

Hope that helps!

**Comment by lukehinds** [comment]
thank you @algesten !
