### ISSUE TITLE
Issues with cookies when using axum locally

### ISSUE THREAD

**Issue by JulianRuiseco** [algesten/ureq#466]
I have been trying to get ureq to allow cookies to be set from Axum today.

Checklist

1) Cookies feature enabled
2) Using agentbuilder and a cookie store I make manually and pass into the agentbuilder
3) Cookies definitely working when using Insomnia to test

Is there a chance that ureq is rejecting the cookies because I am using a localhost path?

**Comment by algesten** [comment]
Hi @JulianRuiseco,

I believe it should work. ureq relies on the `cookie_store` crate to store cookies, and there's even a test in that crate that seems to classify localhost as "secure" https://github.com/pfernie/cookie_store/blob/5ac85c57e7b076c376214ef871592ba41fc3c7c2/src/cookie_store.rs#L1473
