### ISSUE TITLE
Hooks for making TCP connections, and resolving

### ISSUE THREAD

**Issue by ijackson** [algesten/ureq#467]
Hi.  I'm with the [Tor Project](https://www.torproject.org/), working on our RIIR Tor implementation, [arti](https://gitlab.torproject.org/tpo/core/arti).  We would like to make it easy for people to use Tor in their applications.  In particular, it would be nice to be able to use `ureq` with Arti.

Right now that can be done via SOCKS, but that's not very pretty, and results in a pretty complicated setup (especially if you're trying to put this all into a single program).  What would you think about providing a hook API so that a caller of `ureq` could pass in their own thing for making TCP connections?  This seems to be essentially exposing the underlying mechanism that `proxy` uses.

Additionally, DNS resolution would want to be diverted.  A hook for just that would help address #416 too, but for the Tor case it would make more sense for the TCP connection function to take the hostname string and have the DNS resolution done by the connector function.  That would also allow other kinds of stunts if anyone should want them...

Anyway, please let me know what you think.  FTR, the ticket in Arti is [our #287](https://gitlab.torproject.org/tpo/core/arti/-/issues/287)

**Comment by algesten** [comment]
@ijackson This all sounds reasonable, we could look at what API is required for it.

If I understand this correctly, `ureq` can do custom `Tls` connectors via the [recently added API](https://docs.rs/ureq/2.4.0/ureq/struct.AgentBuilder.html#method.tls_connector) for that (barring a bug that is being fixed). However for this to work with `arti` we need to go "one layer down", and also provide a custom `TcpStream`.

Is that right?

**Comment by mcr** [comment]
Also, when using SOCKS or Tor, redirects do not mean opening a new socket.
When doing custom TLS connections, redirects within a host may be acceptable, but ones elsewhere may be forbidden.

**Comment by mcr** [comment]
I just looked into splitting up the http related code (request/response/cookies/middleware/header/body/error) from the connection oriented code into two directories, and eventually maybe into two libraries.
My pub use-fu wasn't strong enough to patch this up easily through "pub crate:..." stuff, but I could try again if there is interest.
In the meantime, for my needs, I'm going to re-implement unit::connect(), but the ownership issues with do_from_stream() is still going to be a problem, I think.
I guess that I have to make the TLS connection cache work somehow.

**Comment by algesten** [comment]
> But the bigger problem is that the line:
> 
> ```
>  let result = Response::do_from_stream(stream, Some(unit.clone()));
> ```
> 
> takes ownership of the stream. If the connection pool can cache the TLS Stream (and for MBEDTLS, I don't think I can yet), then the TLS connection won't get recreated. For Tor, you definitely don't want the connection to be recreated. I think that we need to change this to a ref, but that creates a complex of lifetime issues too.

Hi @mcr I'm trying to follow your thought process, but I got kinda stuck. With HTTP/1.1 we can't multiplex multiple parallel requests/responses over the same socket (HTTP/2 can). We must wait for the response and read _the entire_ response body before we can process the next (response).

`Stream` is the abstraction we're using to represent the bi-directional socket. And since we can't multiplex, we are passing ownership of the instance around. For an already pooled connection this would be:

```
Pool -> Unit::connect_inner -> Response -> PoolReturnRead -> Pool
```

(`PoolReturnRead` is a `std::io::Read` that returns the ownership to the pool once the body is fully read.)

My confusion might all be down to not understanding the finer points of Tor, but for me it sounds strange that "I think that we need to change this to a ref" – because how could it be some shared ownership without also do multiplexing?

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x. In ureq 3.x the entire transport is replaceable. Any kind of connection is possible.

**Comment by ijackson** [comment]
Thanks, that's a useful prompt.  We hadn't noticed these improvements in ureq 3.x.  I've filed a [more specific ticket](https://gitlab.torproject.org/tpo/core/arti/-/issues/1519) against our project, suggesting that we should see about providing some kind of integration of ureq 3 with Arti.

**Comment by algesten** [comment]
@ijackson nice! It will  be very interesting to hear if ureq 3.x works for you. I intend to release some kind of beta version to crates.io any day now. The transport system is not set in stone until we fully release 3.x, so any input you have would be much appreciated.
