### ISSUE TITLE
Relax Sync requirement of ReadWrite

### ISSUE THREAD

**Issue by algesten** [algesten/ureq#474]
Currently `ReadWrite` requires `Sync`.

```
pub trait ReadWrite: Read + Write + Send + Sync + 'static {
    fn socket(&self) -> Option<&TcpStream>;
}
```

Technically we don't need `Sync` because a socket connection will not be used outside a single thread while executing a request/response. The only reason it is `Sync` is because we want `Response`, `Error` etc to be `Sync`, and rust can't see that we're using `stream: Box<Stream>` in a "sync way".

This can be fixed to ease implementation of other TLS providers.

**Comment by algesten** [comment]
One idea I have is to use this in [`Response::stream`](https://github.com/algesten/ureq/blob/main/src/response.rs#L70)

```rs
struct SyncWrap<T> {
    t: T,
}

impl<T> SyncWrap<T> {
    pub fn new(t: T) -> Self {
        SyncWrap { t }
    }

    pub fn into_inner(self) -> T {
        self.t
    }
}

unsafe impl<T> Sync for SyncWrap<T> {}
```

Is this sound?

@jsha do you think it's sound?

**Comment by algesten** [comment]
Maybe needing a bound on T:

```rs
unsafe impl<T> Sync for SyncWrap<T> where T: Send {}
```

**Comment by mcr** [comment]
I would suggest that rather than asking for a reference on the TcpStream, so that DeadlineStream can do stuff to it, that we simply ask for the Connector to do the stuff that DeadlineStream needs done.
