### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by insanitybit** [algesten/ureq#481]
reqwest has an option to force HTTPS. This is particularly useful for redirects as it prevents HTTPS -> HTTP redirects.

https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.https_only

**Comment by algesten** [comment]
I'd be open for such as configuration option on the agent level. @jsha what do you say?

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x. This is solved in ureq 3.x
