### ISSUE TITLE
ureq fails to build with "socks" on windows arm64

### ISSUE THREAD

**Issue by harrisonmetz** [algesten/ureq#485]
Hello. This crate fails to build on windows arm64. I believe the cause is an older version of winapi used by the rust-socks crate. The following PR https://github.com/sfackler/rust-socks/pull/19 should update the rust-socks create with a newer version of winapi. Once that is complete, this create will need to have its version of rust-socks bumped. Thanks.

**Comment by algesten** [comment]
I believe we are still waiting for a new release of rust-sock.

**Comment by harrisonmetz** [comment]
That is correct. The did appear to merge the PR. Should you kindly ask if they can cut a new release since it's depended on here?

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x.
