### ISSUE TITLE
Implement Debug for AgentConfig

### ISSUE THREAD

**Issue by tage64** [algesten/ureq#496]
`fmt::Debug` should be implemented properly for `AgentConfig`. Currently, there's just a `todo!()` inside the `fmt` function in the impl of `fmt::Debug` for `AgentConfig` around line 60-70 in `src/agent.rs`.

This caused a panic while printing the debug representation of `ureq::Agent` inside another panic for me. And panics inside panics aren't that very descriptive and should be avoided.

I know the problem is the field `tls_config: Arc<dyn TlsConnector>` which doesn't implement `Debug` and hence we cannot use `#[derive(Debug)]`. Perhaps the easiest solution is to just print `AgentConfig { ... }` as debug representation. It's at least better than a panic. Another alternative is to format the struct as usual and for the `tls_config` field we just write `tls_config: ...`.

**Comment by jsha** [comment]
Good catch, thanks! We should definitely fix this.
