### ISSUE TITLE
warning when connecting to some https sites

### ISSUE THREAD

**Issue by portno12** [algesten/ureq#499]
`[WARN] Received a ServerHelloDone handshake message while expecting [CertificateRequest]`

i am seeing this when connecting to some sites using tls. i cant see any other issues for this error here and no info in the docs about it. i am using version `2.4.0` with all defaults at the moment.

my code is just `ureq::get()` and then using `copy(&mut resp.into_reader(), &mut BufWriter::new(f))?` to output to a file (saving to a file is also missing from examples)

**Comment by algesten** [comment]
Hi! Thanks for trying out ureq.

Spontaneously it sounds like a broken TLS implementation on the server side, but it would be good to double check. Is there a website you can point us to that shows this behavior?

**Comment by portno12** [comment]
i think you are right. i was hitting a cdn mirror for os packages. when i changed to a non-cdn mirror the issue went away. the cdn in question is this `https://cdn.open bsd.org/pub/Open BSD/` provided by fastly (minus the spaces). i enabled debug output and didnt see anything helpful. fetching any file from there should replicate the issue.

**Comment by algesten** [comment]
Interesting. I just tried `https://cdn.openbsd.org/pub/OpenBSD/snapshots/packages/aarch64/2048-cli-0.9.1.tgz` and I don't see this problem.

I wonder if you have some proxy in between you and that mirror?

What do you see if you do:

`openssl s_client -host cdn.openbsd.org -port 443`

Here's a part of my output:

```
subject=/CN=e.sni-729-default.ssl.fastly.net
issuer=/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Atlas R3 DV TLS CA 2020
---
No client certificate CA names sent
Server Temp Key: ECDH, X25519, 253 bits
---
SSL handshake has read 3480 bytes and written 281 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-CHACHA20-POLY1305
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-CHACHA20-POLY1305
```

**Comment by portno12** [comment]
i dont use a proxy on this network. the system i was running the code from is windows and does not have openssl installed. perhaps something with how ureq and the windows cert store interops?

**Comment by jsha** [comment]
Can you post your full code or a minimized example?

**Comment by portno12** [comment]
ips redacted and spaces added purposely to the urls.

simple example:

```
use simplelog::{LevelFilter, ConfigBuilder, SimpleLogger};

fn main() {
    SimpleLogger::init(LevelFilter::Debug, ConfigBuilder::default().build()).unwrap();
    ureq::get("https://cdn.open bsd.org/pub/Open BSD/snapshots/amd64/SHA256").call().unwrap();
}
```

debug output:

```
> .\target\debug\rust-demo.exe
23:34:25 [DEBUG] (1) ureq::stream: connecting to cdn.open bsd.org:443 at 151.y.y.y:443
23:34:27 [DEBUG] (1) rustls::client::hs: No cached session for DnsName(DnsName(DnsName("cdn.open bsd.org")))
23:34:27 [DEBUG] (1) rustls::client::hs: Not resuming any session
23:34:27 [DEBUG] (1) rustls::client::hs: ALPN protocol is None
23:34:27 [DEBUG] (1) rustls::client::hs: Using ciphersuite Tls12(Tls12CipherSuite { suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, bulk: Aes128Gcm })
23:34:27 [DEBUG] (1) rustls::client::tls12::server_hello: Server supports tickets
23:34:27 [DEBUG] (1) rustls::client::tls12::server_hello: Server may staple OCSP response
23:34:27 [DEBUG] (1) rustls::client::tls12: ECDHE curve is ECParameters { curve_type: NamedCurve, named_group: X25519 }
23:34:27 [WARN] Received a ServerHelloDone handshake message while expecting [CertificateRequest]
23:34:27 [DEBUG] (1) rustls::client::tls12: Server DNS name is DnsName(DnsName(DnsName("cdn.open bsd.org")))
23:34:27 [DEBUG] (1) rustls::client::tls12: Session saved
23:34:27 [DEBUG] (1) ureq::stream: created stream: TcpStream { addr: 10.x.x.x:61883, peer: 151.y.y.y:443, socket: 528 }
23:34:27 [DEBUG] (1) ureq::unit: sending request GET https://cdn.open bsd.org/pub/OpenBSD/snapshots/amd64/SHA256
23:34:27 [DEBUG] (1) ureq::unit: writing prelude: GET /pub/Open BSD/snapshots/amd64/SHA256 HTTP/1.1
Host: cdn.open bsd.org
User-Agent: ureq/2.4.0
Accept: */*
accept-encoding: gzip
23:34:27 [DEBUG] (1) ureq::unit: response 200 to GET https://cdn.open bsd.org/pub/OpenBSD/snapshots/amd64/SHA256
23:34:27 [DEBUG] (1) ureq::stream: dropping stream: TcpStream { addr: 10x.x.x:61883, peer: 151.y.y.y:443, socket: 528 }
```

**Comment by jsha** [comment]
I can't reproduce this on the latest `main` or 2.4.0, on Ubuntu Linux. It's possible this is something odd that happens on Windows. I'll try on my Windows machine when I get a chance.

If you have access to a Linux machine can you try running the same code there and see if you get the same result? That would help us rule in or out something odd about your network.

**Comment by portno12** [comment]
looks like the same in a fedora 36 vm for me so probably something weird happening on my end if the issue cannot be reproduced. my debug log looks the same as above.

i am ok if this gets closed since it may be on my end and not reproducible. when i download the files i can verify the hashes are ok so its not a huge concern for me, i just didnt want this to pop up for users of my application.

**Comment by portno12** [comment]
@jsha i will go ahead and close this since it seems consistent but only with certain mirrors. i am still not clear why but doesn't seem to break anything. i will reopen if it becomes more widespread for me.
