### ISSUE TITLE
Sync bound on ReadWrite

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#515]
Following up the conversation in https://github.com/algesten/ureq/pull/510#issuecomment-1114202093. If we merge #514 I think that is a satisfactory resolution for me, but it's worth having a bit more discussion here. @algesten said:

> With regards to `Sync`, I think we need to have "two directions" in mind.
>
> 1) Types that ureq provides to the user, i.e. `Request`, `Respone`, `Agent`, `Error`. To maximize the utility of ureq, we should strive to have all these as `Sync`. That way the user can "stash away" an Agent or a Response and we would not "taint" the user's context with non-Sync.
>
> 2) Types we expect from the user, i.e. `impl TlsConnector`, `impl Resolver`, `impl Middleware`. For these, we should try to avoid `Sync` as much as reasonable, since that will make it easier for the user to integrate with ureq (we can go even further here in what traits we might be able to avoid, such as `Send`, `'static` etc).

You're right that it's nice to the user to require as few bounds as possible for user-provided objects. But `impl TlsConnector` is notably different than `Resolver` and `Middleware`. For `Resolver` and `Middleware` we expect a wide variety of users to implement them themselves. For `TlsConnector`, there are only a handful of TLS implementations in the world. We can look at the actual implementations to see what bounds are reasonable, and which are burdensome. So far we've looked at three TLS implementations and found that `Sync` is trivial for native-tls and rustls; it is every so slightly non-trivial for mbedtls: the wrapper has to use a Mutex to account for the fact that the library is not full duplex. Given that, I think it makes more sense philosophically to put the burden on the mbedtls ureq adapter rather than on ureq itself.

> We will never have unsafe use directly in ureq, but crates we depend upon will always have it. `sync_wrapper` is entirely sound (I think it could be included in Rust std lib). This is the current situation with geiger.

Yes, crates we depend upon will always have some unsafe. What's the reason we accept `unsafe` in crates we depend upon but not in our own crate? Here's my reasoning: some things can't be done without it. For instance, `flate2` uses FFI to depdend on a highly optimized system library. Similarly `ring` uses FFI to call out to highly optimized assembly. `log` uses `unsafe` to mutate a global static. We depend on those libraries because (a) we need them to get things done, and (b) they are heavily depended upon that we expect the soundness of their unsafe blocks has been looked at by a decent number of people.

By contrast, while I _believe_ [`sync_wrapper`](https://docs.rs/sync_wrapper/latest/sync_wrapper/) is sound, it's not very well-used. So I'm relying mostly on the forum thread linked from its documentation, plus our own evaluation. Comparing that with the relatively small benefit we get from it, and the inherent risk of additional dependencies, I think it makes sense to remove it.

Also, for clarity, when I talk about the inherent risk of additional dependencies, I'm thinking of things like [`event-stream`](https://snyk.io/blog/a-post-mortem-of-the-malicious-event-stream-backdoor/).

**Comment by algesten** [comment]
> Given that, I think it makes more sense philosophically to put the burden on the mbedtls ureq adapter rather than on ureq itself.

Fair enough. We don't need to treat all of these the same.

> Yes, crates we depend upon will always have some `unsafe`. What's the reason we accept unsafe in crates we depend upon but not in our own crate?

I reason in a similar way to you. Ultimately _nothing_ can be done without unsafe. A hardcode stance would be to only allow the unsafe in `std` and `core` – no third party crates. However being pragmatic there certainly are crates (with unsafe) that are of high enough quality that we can depend on them. We just need to be vigilant with our deps.

**Comment by jsha** [comment]
So are you okay with adding back the Sync bound for now? I figure this way: if we do a release with the Sync bound, and later find that it's a big problem for people, we can always remove the bound. But once we've done a release we can't add the bound afterwards without an API break.

**Comment by lolgesten** [comment]
I didn't realize this wasn't settled since I was quite happy with the current situation :) 

Are you proposing we add back the Sync bound `TlsConnector` only? If so, please go ahead and make a PR. I'll accept it since we can remove it again in the future if need be.

**Comment by algesten** [comment]
I didn't realize this wasn't settled since I was quite happy with the current situation :) 

Are you proposing we add back the Sync bound `TlsConnector` only? If so, please go ahead and make a PR. I'll accept it since we can remove it again in the future if need be.

**Comment by jsha** [comment]
Thanks! I appreciate your flexibility on this. I was somewhat happy with the current situation, but I still found it somewhat inelegant. I am very happy with the situation now that we have Sync back on ReadWrite; and of course am open to change as we get feedback.
