### ISSUE TITLE
Tutorial or example on how to use CookieStore?

### ISSUE THREAD

**Issue by narigama** [algesten/ureq#525]
I see in 2.0.0, the built in `Agent::set_cookie` was dropped in favour of using CookieStore, but I don't see an example in the docs/examples of how to use it. Can I get some guidance on how to add cookies to the Agent as to enable them in my requests?

**Comment by algesten** [comment]
I'm not clear why we only exposed a read-only version of the cookie store. The code uses an `RwLock`, which means we can have agent requests "in flight" while reading. With the provisio that write permission would lock down any current requests interacting with the cookie store, we could add a mut version too.

@jsha Thoughts?

**Comment by jsha** [comment]
We removed `Agent::set_cookie` here: https://github.com/algesten/ureq/commit/1f8bb532fee3ae290aaabfb085dbfefd14a03003

After discussion here: https://github.com/algesten/ureq/issues/203#issuecomment-716385310

The short version is: Agent is meant to be shared widely across your program, to maximize connection reuse. It uses internal mutability to achieve connection reuse. However, it would be surprising if component A expected a logged-out state, but component B called `set_cookie` on their shared Agent, changing it to a logged-in state.

Looking at this decision a second time, I'm realizing there's an important inconsistency: component A can make requests and receive responses that modify the cookie jar (for example POSTing to a login form), and that will modify the shared state in the same potentially surprising way.

To address the immediate problem: @BoydstonNicholas outlines a good approach. @BoydstonNicholas for your use case, is it practical to maintain two Agents, one that has no cookies, and one that is built later with cookies based on user actions?

**Comment by algesten** [comment]
@jsha Amazing that I managed to blank this discussion.

As you point out, we're in a half way state still.

The question: is Agent a state boundary? Either it is, in which case we might as well allow mutation. Or it isn't, in which case we nees to think more about how cookies are handled.

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x. We are not going to re-export cookie store in 3.x
