### ISSUE TITLE
Avoid once_cell Lazy call if not using the default TLS config

### ISSUE THREAD

**Issue by shollwedel** [algesten/ureq#529]
I am playing around with writing a C FFI wrapper for ureq and was doing some memory usage testing. I noticed that the TLS config is always allocated even if it is used which results in a bit higher memory usage than needed. I have added a way to explicitly set the TLS config with AgentBuilder to avoid this extra allocation. Is that something of interest to others?

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x.
