### ISSUE TITLE
unix domain socket support?

### ISSUE THREAD

**Issue by futurist** [algesten/ureq#538]
Don't find in the docs about unix domain socket support. Can provider an example for this?

**Comment by jsha** [comment]
Not currently, no.

**Comment by cablehead** [comment]
With `ureq`'s focus on simplicity, do you think there'd be interest in accepting a PR to add unix domain socket support?

**Comment by algesten** [comment]
What would the API look like?

**Comment by cablehead** [comment]
Adding to the mix of ideas:

```url
http+unix://%2Ftmp%2Fapi.sock/service?query=1
```

- `scheme`: `http+unix://`, this allows https to still be conveniently expressed
- `authority`: `%2Ftmp%2Fapi.sock`, sock path, requires the path to be URL encoded
- `path`: `/service?query=1`

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x. In 3.x the transport is completely replaceable. This should be very solvable.

**Comment by MggMuggins** [comment]
I gave this a try with `3.0.0-rc2` and ran into issues parsing `http+unix` URIs with the `http` crate. It [currently does not support](https://github.com/hyperium/http/pull/528) percent-encoded host components. I might take a look at implementing the requested checks but right now it doesn't look like any of the suggested syntaxes are viable.

Even if `http` would merge support for percent-encoded URIs, ureq still [needs to add a proto](https://github.com/algesten/ureq/blob/main/src/run.rs#L317):
```patch
diff --git a/src/proxy.rs b/src/proxy.rs
index 7694713..8b771c2 100644
--- a/src/proxy.rs
+++ b/src/proxy.rs
@@ -23,6 +23,7 @@ pub(crate) enum Proto {
     Socks4,
     Socks4A,
     Socks5,
+    Unix,
 }
 
 impl Proto {
@@ -31,6 +32,7 @@ impl Proto {
             Proto::Http => 80,
             Proto::Https => 443,
             Proto::Socks4 | Proto::Socks4A | Proto::Socks5 => 1080,
+            Proto::Unix => u16::MAX,
         }
     }
 
@@ -279,6 +281,7 @@ impl TryFrom<&str> for Proto {
             "socks4a" => Ok(Proto::Socks4A),
             "socks" => Ok(Proto::Socks5),
             "socks5" => Ok(Proto::Socks5),
+            "http+unix" => Ok(Proto::Unix),
             _ => Err(Error::InvalidProxyUrl),
         }
     }
@@ -302,6 +305,7 @@ impl fmt::Display for Proto {
             Proto::Socks4 => write!(f, "SOCKS4"),
             Proto::Socks4A => write!(f, "SOCKS4a"),
             Proto::Socks5 => write!(f, "SOCKS5"),
+            Proto::Unix => write!(f, "UNIX"),
         }
     }
 }
```

Can this be reopened? I'll see about updating that PR to `http`.

**Comment by MggMuggins** [comment]
To be clear, the above doesn't stop one implementing a Connector/Transport/Resolver that contains the socket path and just ignores the host part of the URL. But it would be convenient if ureq could make `http+unix` URIs "just work".

**Comment by colinmarc** [comment]
I just spent a day trying to get this work, and couldn't. There's no way I could find to avoid the check in `default_port`:

https://github.com/algesten/ureq/blob/1ce334d329d5bdcc8f36126f34c7f61ba851c409/src/util.rs#L49-L59

Which always results in a parsing error:

https://github.com/algesten/ureq/blob/1ce334d329d5bdcc8f36126f34c7f61ba851c409/src/util.rs#L319-L321

You could just pass a completely fake uri to the agent, I guess, but that's pretty ugly. I think this issue should be reopened.

**Comment by algesten** [comment]
@colinmarc  You're right, this is too strict. I've opened a more appropriate issue for it.
