### ISSUE TITLE
Redesigning PoolReturnRead

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#559]
PoolReturnRead is important because we need to be able to hand something back to the user that (a) implements Read and (b) returns the Stream to the Pool as soon as it is correct to do so. But it relies on a property of the Read interface that is not actually guaranteed and in fact is often not true. It relies on upstream Readers always reading until they get to `Ok(0)`. We [tried to fix this with the `Done` trait](https://github.com/algesten/ureq/pull/509), for the LimitedRead case. But it's come up again in https://github.com/algesten/ureq/issues/549 and https://github.com/algesten/ureq/issues/555, which makes me think we are using the wrong abstraction.

PoolReturnRead only ever wraps two types: `LimitedRead` and `ChunkDecoder`. We can move the "return to pool" logic down a level and make those two types responsible for returning their Stream when it is viable. For instance, `LimitedRead` could have an `Option<R>`, and so long as it has bytes left to read and that `Option` is `Some`, it would read from the inner reader. If any read would leave zero bytes left, it would `take()` the Option and return it to the pool before returning from `read()`. For `ChunkedDecoder` we would need a `BufRead` as the inner reader, so that it could look ahead and see if the next bytes are the end-of-stream indicator, and do the same thing.

The end result of these would be that in almost all cases, the stream would be returned to the pool on the second-to-last read (the one returning `Ok(n)`), not the last read (returning `Ok(0)`). And if the user never calls a read that returns `Ok(0)`, we don't have to care.

**Comment by algesten** [comment]
Sounds good overall.

> The end result of these would be that in almost all cases, the stream would be returned to the pool on the second-to-last read (the one returning Ok(n)), not the last read (returning Ok(0)). And if the user never calls a read that returns Ok(0), we don't have to care.

Doesn't this mean that we could have garbage data after the body? How do we "guarantee" the `Stream` is correct for the next pool reuse?

**Comment by jsha** [comment]
When we return the Stream to the pool, we can check that the `inner` `BufReader`'s buffer is empty.

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x.
