### ISSUE TITLE
`AgentBuilder::new` panics (possibly because of ill-formed certificates)

### ISSUE THREAD

**Issue by wolthom** [algesten/ureq#563]
Recently, the following issue showed up with the `juliaup` program (more info [here](https://github.com/JuliaLang/juliaup)):
https://github.com/JuliaLang/juliaup/issues/487

The backtrace suggests, that the panic happens during the call to `AgentBuilder::new`. We suspect this could be related to encountering a bad certificate. David found some potential clues here:
https://github.com/rustls/rustls-native-certs/issues/15 when a 

This issue from `reqwests` seems to be related as well:
https://github.com/seanmonstar/reqwest/pull/1316

Is this something you are aware of or could take a look at? Maybe the `reqwests` solution could work here as well.
Thanks!

**Comment by jsha** [comment]
Thanks for the report! We definitely shouldn't panic here. I think the approach of logging an error and continuing is correct. If the malformed root cert was needed to validate a connection, that will show up at request time.
