### ISSUE TITLE
Release 2.6.0

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#567]
Later today I'll merge #565. After that I'd like to work on cutting another release - update the CHANGELOG, then tag it and publish. @algesten is there anything you want to get into the next release that's not already landed?

**Comment by algesten** [comment]
@jsha what about this one? https://github.com/algesten/ureq/pull/544

**Comment by jsha** [comment]
Oh good reminder, thanks!

**Comment by algesten** [comment]
Thanks for reviewing #544. I don't think we need to stall the release on that one. We just want the changes you're making to pool and then go. 

Nice work on this release!

**Comment by jsha** [comment]
Done: https://crates.io/crates/ureq/2.6.0

**Comment by lolgesten** [comment]
Great work! Thanks!
