### ISSUE TITLE
boringssl support

### ISSUE THREAD

**Issue by wireguard-dev** [algesten/ureq#576]
Hello! How about boringssl support so we can use ureq to impersonate chrome?

**Comment by jsha** [comment]
I think the best way to implement that would be to implement the [TlsConnector trait](https://docs.rs/ureq/latest/ureq/trait.TlsConnector.html) using BoringSSL, and publish that as an independent crate. Is that something you're interested in working on?

**Comment by jsha** [comment]
No problem! I can tell you that this is not likely to be a priority for us, but we do provide a way for anyone to bring their own TLS implementation using Rust's trait system. When you or a friend get to the point you feel comfortable doing that, ureq will be here for you. :-)

**Comment by jsha** [comment]
Closing for now. Good luck with your Rust journey and I hope you get to the point where you feel confident implementing this. 🚀
