### ISSUE TITLE
Downloading with a status bar / progress updates

### ISSUE THREAD

**Issue by tgross35** [algesten/ureq#577]
Hey all,

After some trial and error I figured out how to do a download with `ureq` that does some sort of status updates. Figured it may be useful to people searching through the issues here (as I did before figuring it out), so here is the gist:

https://gist.github.com/tgross35/06c8205ee46f330c32958f0db4971d65

**Comment by tgross35** [comment]
Actually, er, I'm going to reopen this since I have a question

The `std::io::Read` docs say that you can't rely on the result of `read_bytes` returning 0 to indicate that the stream is closed. Does `ureq` provide a better way to hook into this information?

**Comment by jsha** [comment]
> The std::io::Read docs say that you can't rely on the result of read_bytes returning 0 to indicate that the stream is closed. Does ureq provide a better way to hook into this information?

The Read impl returned by ureq treats Ok(0) as meaning "end of response." We should document that, but you can rely on it now.

**Comment by tgross35** [comment]
That's great to know, thanks for the clarification.

Is there anything that avoids getting a 0 in the middle of the stream somewhere, like if there's a temporary connection slowdown and there's nothing to write? Likely a nonissue in practice, but I'm curious if there's a way to mitigate it.

**Comment by jsha** [comment]
In blocking I/O (which ureq uses), when there is nothing to read off the connection, reading will block. So for instance if there is nothing to read for a minute, a single read call might wait for a minute before returning. It won't return Ok(0).

In non-blocking I/O, at the syscall level, reading from a connection where there's no data available still won't return Ok(0) - it will return EAGAIN or EWOULDBLOCK.

**Comment by tgross35** [comment]
Makes sense, thank you!
