### ISSUE TITLE
Docs incorrect about serde_derive?

### ISSUE THREAD

**Issue by n8henrie** [algesten/ureq#579]
The docs seem to suggest that one can add / use `serde_derive` as an alternative to `serde` (in my case for the `json` stuff): 

https://github.com/algesten/ureq/blob/032bfb4b276cf133b727dbb2746f558a96e56a15/src/response.rs#L468

> An alternative way to is to use the `serde_derive` crate.
Put this in Cargo.toml: serde_derive = "1"
use serde_derive::{Deserialize};

But it doesn't seem to work. Am I misunderstanding how this is supposed to work?

```console
$ cargo new foo && cd $_
$ cargo add ureq --features=json
$ cargo add serde_derive
$ cat <<'EOF' > src/main.rs
use serde_derive::Deserialize;

#[derive(Deserialize)]
struct Response;

fn main() {
    todo!()
}
EOF
$ cargo build
   Compiling foo v0.1.0 (/private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.8KxiUrC2C9/foo)
error[E0463]: can't find crate for `serde`
 --> src/main.rs:3:10
  |
3 | #[derive(Deserialize)]
  |          ^^^^^^^^^^^ can't find crate
  |
  = note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0463`.
error: could not compile `foo` due to previous error
```

I may be just using it wrong, but I'd be happy to submit a documentation PR if anything needs updating.

**Comment by jsha** [comment]
Thanks for the report! I honestly don't know why that error happens, since serde_derive should pull in serde transitively. But it looks like the documented way to use serde's derive macros is by importing them from serde, not serde_derive:

https://serde.rs/derive.html

Probably we should remove the mention of serde_derive. Thoughts @algesten ?

**Comment by algesten** [comment]
@jsha Yes. `serde_derive` was "the old way", which I think still worked. However increasingly people (including myself) are using only `serde` with the feature `derive` turned on. We should change the docs to reflect this.

**Comment by n8henrie** [comment]
Figured something out -- this works (without depending on `serde` itself):

```rust
use serde_derive::Deserialize;

#[derive(Deserialize)]
#[serde(crate = "ureq::serde")]
struct Response;

fn main() {
    todo!()
}
```

Does that PR for the docs look okay?
