### ISSUE TITLE
IP Common Name support coming to rustls

### ISSUE THREAD

**Issue by dontlaugh** [algesten/ureq#586]
Not a bug, but I wanted to give you all a heads up

https://github.com/rustls/rustls/issues/184#issuecomment-1385458603

Relates to (I believe) https://github.com/algesten/ureq/issues/393

Thank you all again for maintaining this simple, beautiful **synchronous** library.

**Comment by algesten** [comment]
Excellent! We will upgrade RusTLS promptly when this lands!

Thanks!
