### ISSUE TITLE
Customizable `Response`s for middlewares

### ISSUE THREAD

**Issue by kade-robertson** [algesten/ureq#589]
Hello!

This is partially related to https://github.com/algesten/ureq/issues/363 in terms of my personal use case, but I wanted this to be more of a generic request.

Currently, it isn't _really_ possible to construct anything but a basic, text-only `Response` object (as in, one not generated by making a request). I've run into this limitation recently on one of my projects -- I've implementing a caching middleware [here](https://github.com/kade-robertson/ddragon/blob/34012e522e615c3669d47c583899effc3a80231d/src/cache_middleware.rs#L22) as a very basic replacement for the functionality I can get from something like [http-cache-reqwest](https://github.com/06chaynes/http-cache). This generally works okay for UTF-8 data such as serialized JSON responses like I primarily deal with, but falls apart when downloading images. I ended up having to add an escape hatch and a custom caching wrapper around my request to deal with that particular instance.

The current "faking" mechanism is _almost_ what I'd expect, but the missing piece here is accepting a `&[u8]` content body and (possibly) a more structured way of specifying headers like `Content-Type`. 
- Maybe this doesn't make sense to overload `Response::new` with and rather a `ResponseBuilder` or some `.set_body(&mut self)`-like method would be the way to go. 
- Maybe `Response` and `Request` can `#[derive(Serialize, Deserialize)]`?

This might be leaning towards making this project more complex then it aims to be, but I think given that a middleware trait already exists, it makes sense to flesh this out a bit more than it is currently.

**Comment by kade-robertson** [comment]
Looking at this a bit more, maybe what makes the most sense is using [`http::Response`](https://docs.rs/http/latest/http/response/struct.Response.html) as the tool for constructing the response, and have this crate's `Response` implement `From<http::Response<T>>`. 
- It seems reasonably thorough and provides the level of customization I'd be looking for I think
- Relatively lightweight in terms of build time impact
- Doesn't pull in too many additional dependencies
- MSRV of the current version (`0.2.8`) is below what _seems_ to be the MSRV of this version (1.53 or 1.56 based on the MSRV issue here)
- Reasonably easy to put behind a feature if this isn't desired to be included by default

**Comment by algesten** [comment]
Hi! Thanks for thinking about this!

I think an optional dependency on the http crate would be good. Something that both allows conversion in both directions for both `Request` and `Response` (if possible, I haven't thought about this deeply. I.e. we would provide:

```rs
impl<T: what bound?!> From<http::Request<T>> for Request
impl From<Request> for http::Request<something good>
impl<T: what bound?!> From<http::Response<T>> for Response
impl From<Response> for http::Response<something good>
```

I guess the main question is what `T` and `something good` is.

**Comment by kade-robertson** [comment]
Looking at how other libraries do this:

- `reqwest` implements `impl<T: Into<Body>> From<http::Response<T>> for Response`, where their body is more or less formatted how they want, and their body implements `impl From<hyper::Body> for Body` since their response is essentially a wrapper on `hyper`'s response. They also implement some convenience conversions from `Bytes`, `Vec<u8>`, `&'static [u8]`, `String`, `&'static str`, and files for their body.

- `surf` is in a bit of an easier scenario, where their `Response` is a wrapper around `http_client::Response`. You can craft a custom `surf` response with `Response::new(my_http_client_response)`. Given that `surf` is entirely based on using the `http-rs` project's various crates I don't think their implementations necessarily match what would work for this repo.

Based on how this project works (at least from what I can gather, I might be missing something), `Stream` is the closest thing that could be used as a reasonable bound, i.e. `impl<T: Into<Stream>> From<http::Response<T>> for Response`, but I think the issue there is the stream isn't really just the body -- it's the entire response. So the way to do this with only new, feature-gated code would be to have something like an `impl<T: AsRef<[u8]>> From<http::Response<T>> for Stream` (this may be challenging), and then have `impl From<Stream> for Response` just call `.do_from_stream()`. 

---

That doesn't _feel_ particularly great to me but it avoids messing with the structure of the repo too much. Might also just be overthinking this. Given the reader for the body is fairly generic, this could be as simple as:

```rust
impl<T: Into<http::Body>> From<http::Response<T>> for Response {
    fn from from(r: http::Response<T>) -> Response {
        let code = r.status();
        let body = r.take_body();
        Response {
            url: "https://example.com".to_owned(),
            status_line: format!("{} {}", code, code.canonical_reason()),
            index: ResponseStatusIndex { http_version: 0, response_code: 0 },
            headers: r.iter().map(|h| h.into()),
            reader: body.into_reader(),
            remote_addr: () // make something up?,
            history: vec![]
        }
    }
}
```

The type for the reader `http::Body` creates is a bit different than the reader Response expects (`Box<dyn AsyncBufRead + Unpin + Send + Sync + 'static>`). A similar approach would probably work for `Request` but I haven't looked at that one as much.

In terms of the reverse direction, `http::Body` can be converted to/from a reader, string, or bytes, so it should be pretty compatible with this crates' `body::Payload`, leading to something like `impl From<Request> for http::Request<http::Body>`

**Comment by algesten** [comment]
I'm with you overall. The one thing I would want to look at closer is to not expose any of the internal types like `Stream` publicly. Generally I prefer to keep the API surface the same size as now.

If we need new exposed types, I rather wrap things like Stream in some level of abstraction outwards.

**Comment by kade-robertson** [comment]
I have an example I've come up with -- not amazing but seems to work reasonably well for `Response` at least. Given that some steps that have to be taken are fallible, I implemented this as `TryFrom` instead: https://github.com/algesten/ureq/compare/main...kade-robertson:ureq:http-types

```rust
impl TryFrom<http_types::Response> for Response {
    type Error = io::Error;

    fn try_from(mut value: http_types::Response) -> Result<Self, Self::Error> {
        let code = value.status();
        let headers = value
            .iter()
            .map(|(name, value)| Header::new(name.as_str(), value.as_str()))
            .collect::<Vec<_>>();
        let version = value
            .version()
            .unwrap_or(http_types::Version::Http1_1)
            .to_string();
        if let Ok(body_bytes) = futures_lite::future::block_on(value.body_bytes()) {
            Ok(Response {
                url: "https://example.com".parse().unwrap(),
                status_line: format!("{} {} {}", version, code, code.canonical_reason()),
                index: ResponseStatusIndex {
                    http_version: version.len(),
                    response_code: version.len() + code.to_string().len(),
                },
                status: code.into(),
                headers,
                reader: Box::new(Cursor::new(body_bytes)),
                remote_addr: SocketAddr::new(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), 80),
                history: vec![],
            })
        } else {
            Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "response body could not be read",
            ))
        }
    }
}
```

I do have some gripes, mainly around having to introduce `futures-lite` to be able to retrieve the request body. If this looks relatively reasonable, I can flesh out a full PR -- I think this can reasonably be applied to complete the implementations you had outlined earlier.

**Comment by kade-robertson** [comment]
I've created https://github.com/algesten/ureq/pull/591 as a preliminary look at what this might look like.

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x. The new version is based on the http crate which probably helps here.
