### ISSUE TITLE
Custom TcpStream pass

### ISSUE THREAD

**Issue by ashat1701** [algesten/ureq#592]
Hi! While searching for rust http library found this. Library is great, because I need sync requests without any async code. But I can't find where can i pass custom tcpstream or sslstream. For example i need to bind socket to network interface. I didn't find where can i explicitly pass stream into Agent (or maybe some lambda for socket creation). Can you help me find a way to do this.

**Comment by algesten** [comment]
Hi @ashat1701! Welcome to ureq!

We don't have what you ask for exactly, but I'm wondering whether the custom-tls example might be usable. https://github.com/algesten/ureq/blob/main/examples/custom-tls.rs

There's also the mbedtls example for a more full fledged impl.

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x. In 3.x the transport is completely replaceable.
