### ISSUE TITLE
Borrow checker : getting header and json (not ureq)

### ISSUE THREAD

**Issue by matclab** [algesten/ureq#593]
First, thank you for this nice crate.

I need to compute a value which depends upon a header and json body, but once the header is accessed with for example `response.header("Token");`, then `response` is borrowed, and I can not access `response.into_json()` anymore.

I'm still a rust beginner, so I may have missed something obvious, but any help would be greatly appreciated.

**Comment by algesten** [comment]
Hi @matclab! Welcome to ureq!

This problem is indeed not ureq specific, but more generically how to deal with borrowed values in Rust. Generally the solution is to make your own copy of the data you need (that your code owns).

It would look like this:

```rs
fn main() {
    let response = ureq::get("http://example.com").call().expect("call to succeed");
    let Some(token) = response.header("Token") else {
        println!("Token header missing in response");
        return;
    };
    let token = token.clone(); // make your own copy.
    // response is not borrowed anymore.
    let body = response.into_json();
   ...
}
```

**Comment by matclab** [comment]
Thank you @algesten, your example indeed works,  but trying to use the cloned `token` with for example:

```rust
fn main() -> Result<()> {
    let response = ureq::get("http://example.com").call().expect("call to succeed");
    let Some(token) = response.header("Token") else {
        println!("Token header missing in response");
        return Ok(());
    };
    let token = token.clone(); // make your own copy.
    // response is not borrowed anymore.
    let body = response.into_json()?;
    if  token == "" {
        Ok(body) }
    else {
        Ok(())
    }
}
```

Leads to:
```
   Compiling ureqtest v0.1.0 (/home/clabaut/tmp/ureqtest)
error[E0505]: cannot move out of `response` because it is borrowed
  --> src/main.rs:10:16
   |
4  |     let Some(token) = response.header("Token") else {
   |                       ------------------------ borrow of `response` occurs here
...
10 |     let body = response.into_json()?;
   |                ^^^^^^^^ move out of `response` occurs here
11 |     if  token == "" {
   |         ----- borrow later used here

For more information about this error, try `rustc --explain E0505`.
error: could not compile `ureqtest` due to previous error
```

**Comment by algesten** [comment]
Sorry. instead of clone try `to_string()`

**Comment by matclab** [comment]
Ah yes, it did it. I was pretty sure I've tried it, but obviously not !
I still have to understand why the `clone` didn't` work…

Thanks a lot for your help !
