### ISSUE TITLE
Timeout for connecting to a host

### ISSUE THREAD

**Issue by shahn** [algesten/ureq#595]
This might be similar to #79, but occurs even if no DNS name resolution is happening. Specifying a timeout does not work, ureq waits until the request is failed by the ~~operating system~~ default agent configuration.

**Comment by shahn** [comment]
The problem seems to stem from `connect_host()` in stream.rs. timeout_connect is checked, which is trivially true due to being a default configuration item.

**Comment by shahn** [comment]
Indeed, a crude patch like this fixes it:

```
--- a/src/request.rs
+++ b/src/request.rs
@@ -1,5 +1,6 @@
 use std::io::Read;
 use std::{fmt, time};
+use std::sync::Arc;
 
 use url::{form_urlencoded, ParseError, Url};
 
@@ -59,6 +60,7 @@ impl Request {
     /// Sets overall timeout for the request, overriding agent's configuration if any.
     pub fn timeout(mut self, timeout: time::Duration) -> Self {
         self.timeout = Some(timeout);
+        Arc::make_mut(&mut self.agent.config).timeout_connect = Some(timeout);
         self
     }
 
```

but changing the agent config like that seems surely wrong

**Comment by algesten** [comment]
Hi there! Thank you for looking at ureq!

The default agent configuration doesn't do what you want to here. Deliberately ureq doesn't allow you to modify the default agent config. Instead you must create a new agent that you use to run your requests.

See example here https://docs.rs/ureq/2.6.2/ureq/struct.AgentBuilder.html#method.timeout_connect which I think does what you want.

**Comment by shahn** [comment]
Hi algesten, understood wrt. API design. I still think there might be one bug and one potential documentation improvement:

bug:
`connect_host()` in stream.rs checks a condition that can never be false, there will always be a connect timeout. The problem stems from AgentConfig.timeout_connection being an Option<Duration> which never uses None (there is no way to unset the default timeout via any code path I could find).

documentation improvement:
the documentation for Request::timeout() should not say "overall timeout", but rather mention that there are some other timeouts which are handled by the agent and refer to it for customization

Happy to provide patches with fixes if you are interested

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x. In ureq 3.x the timing values are completely overhauled and there is a timeout for connecting to a host.
