### ISSUE TITLE
Does ureq support Options http method?

### ISSUE THREAD

**Issue by qihaiyan** [algesten/ureq#598]

**Comment by algesten** [comment]
Hi!

OPTIONS does work, you just need to set the method yourself. See example here: https://docs.rs/ureq/2.6.2/ureq/fn.request.html

**Comment by qihaiyan** [comment]
> Hi!
> 
> OPTIONS does work, you just need to set the method yourself. See example here: https://docs.rs/ureq/2.6.2/ureq/fn.request.html

OK, thanks
