### ISSUE TITLE
overall_timeout_reading_json fails with serde_json 1.0.94

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#602]
We have a unittest failing in CI. This was initially confusing because it was not failing for me locally. I realized I had a Cargo.lock locally with older versions of various dependencies. Removing the Cargo.lock caused the test failure to reproduce. I wound up tracking it down to serde_json 1.0.94. There seems to have been a change so our code that downcasts errors from serde's Error::source no longer works.

**Comment by joshstoik1** [comment]
For reference: https://github.com/serde-rs/json/issues/1012
