### ISSUE TITLE
How to read the response body of a post request

### ISSUE THREAD

**Issue by abcjeff** [algesten/ureq#616]
Hello,
I'm trying to get the response body of a post request. But my code doesn't work:

                let resp = ureq::post("http://mywebapp")
                    .set("Content-Type", "application/x-www-form-urlencoded")
                    .send_string("getmyresponse=");
                let body = resp.into_string();

This is the first time I use ureq and I read all the document. The into_string() method seems to be the way to get the response body text, but it doesn't work (error: no method named `into_string` found). So what is the correct way to get response text?
Thanks for any help.

Nevermind, looks like I just need to add unwrap() at the end of each line!

**Comment by jsha** [comment]
Welcome to ureq!

> Nevermind, looks like I just need to add unwrap() at the end of each line!

That's correct. :-D

Even better, if you are inside a function that returns the right kind of Result, you can use the `?` operator documented here: https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-the--operator
