### ISSUE TITLE
Slightly confusing example with into_reader, am I missing something?

### ISSUE THREAD

**Issue by fgimian** [algesten/ureq#619]
Hey there, thanks so much for this library! 😄 

I had some slight difficulty understanding why `take` is used in this example: https://github.com/algesten/ureq/blob/main/src/response.rs#L258

I've placed the example below with some thoughts (marked with `FG`):

```rust
    // FG: You're obtaining the content length which may be any size,
    // FG: even larger than 10_000_000 bytes.
    /// let len: usize = resp.header("Content-Length")
    ///     .unwrap()
    ///     .parse()?;
    ///
    // FG: The vector is allocated with a capacity equal to content length.
    /// let mut bytes: Vec<u8> = Vec::with_capacity(len);
    /// resp.into_reader()
    // FG: Here you're restricting how many bytes are being read to 10_000_000
    // FG: which means that responses longer than this will not fill the vector.
    ///     .take(10_000_000)
    ///     .read_to_end(&mut bytes)?;
```

Is the purpose of `take` to limit the response to a certain size?  If so, would it be a better approach to set the capacity to the minimum of `len` and `10_000_000` or excluding `take` from this example to avoid confusion?

Please forgive me if I'm missing something 😄 
Fotis

**Comment by jsha** [comment]
Ooh, good catch. Thanks for pointing that out! We should skip reading the
content length and do the take(), plus a read_to_string().

**Comment by fgimian** [comment]
> Ooh, good catch. Thanks for pointing that out! We should skip reading the content length and do the take(), plus a read_to_string().

Sweet, makes sense! Thanks heaps for the quick reply. 😄

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x.
