### ISSUE TITLE
Proxy env variables

### ISSUE THREAD

**Issue by davidiw** [algesten/ureq#62]
Was curious about your thoughts of having the proxy code support reading from environmental variables (http_proxy, https_proxy)? Easy enough to do it in my library, but I wanted to sync in here first to see if it made sense to upstream it.

**Comment by algesten** [comment]
I'm in two minds. 

On the one hand, nothing in ureq picks up config from env vars, one could maybe argue that some request config could be env (timeouts comes to mind). From that perspective it's cleaner to keep as is.

On the other hand, I know proxy settings are a special case, and they are many times just magically picked up by apps and libs.

I personally haven't been in many situations where proxies are needed, so my views on this are not reliable. I would ask others like yourself, to guide me on whether this is a good idea or not.

We could for instance do a quick look into some of the other async request libraries to see what they do. What do you think?

**Comment by davidiw** [comment]
Yeah, I am of two minds as well. Since an implicit proxy can be ultra confusing, but many times is expected at least from users. On the flip side, it can leave developers scratching their head. What was your plan for hreq?

Reqwest does this implicitly: https://github.com/seanmonstar/reqwest/blob/master/src/proxy.rs#L596

Perhaps we could find a balance between the two where one would explicitly have to set a flag in the request to use environment flags for proxy if available?

**Comment by algesten** [comment]
@davidiw That sounds like a good compromise!

**Comment by davidiw** [comment]
Fantastic! Just a heads up, my colleague hacked what he needed for now, so work on this will be delayed.

**Comment by algesten** [comment]
Close in favor of #322 where there is more discussion.
