### ISSUE TITLE
DNS problems with ureq on github.com in rootless Docker container built with muslrust

### ISSUE THREAD

**Issue by KonradHoeffner** [algesten/ureq#645]
I am building a Docker image around a Rust application that uses `ureq::get(filename).call()?.into_reader()` to download the file `https://github.com/annosaxfdm/ontology/releases/latest/download/anno.ttl`.
All is fine except when the image is build with musl *and* the Dockerfile is run in rootless mode, then it reports `Dns Failed: resolve dns name 'github.com:443': failed to lookup address information: Name does not resolve.`.

The issue is similar to the one reported in <https://github.com/alpinelinux/docker-alpine/issues/155>, however the issue persists even when I exchange the runtime from alpine to busybox.
In fact, with alpine, I cannot even download the file manually from within the container but with busybox a manual download works, but the Rust application inside the container still cannot.

I hope it is OK to report it in this repository because it is a very specific edge case that touches several components (musl, DNS, ureq and rootless docker).
If this issue is in fact unrelated to ureq, then I'm sorry and feel free to close it.

## Dockerfile that produces the error:

```
# syntax=docker/dockerfile:1
FROM clux/muslrust:1.73.0-nightly-2023-08-01 AS chef
USER root
RUN cargo install cargo-chef
WORKDIR /app

FROM chef AS planner
ARG CARGO_INCREMENTAL=0
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
ARG CARGO_INCREMENTAL=0
COPY --link --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --target x86_64-unknown-linux-musl --recipe-path recipe.json
COPY . .
RUN cargo build --release --target x86_64-unknown-linux-musl

FROM busybox AS runtime
RUN addgroup -S myuser && adduser -S myuser -G myuser
COPY --link --from=builder /app/target/x86_64-unknown-linux-musl/release/rickview /usr/local/bin/
USER myuser
WORKDIR /app
RUN mkdir -p data && touch data/kb.ttl
CMD ["/usr/local/bin/rickview"]
```

## Dockerfile that works fine (but is several times larger):

```
# syntax=docker/dockerfile:1
FROM rust:1 AS chef
USER root
RUN rustup toolchain install nightly && rustup default nightly
RUN cargo install cargo-chef
WORKDIR /app

FROM chef AS planner
ARG CARGO_INCREMENTAL=0
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
ARG CARGO_INCREMENTAL=0
COPY --link --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN cargo build --release --bin rickview

FROM debian:stable-slim AS runtime
COPY --link --from=builder /app/target/release/rickview /usr/local/bin/rickview
WORKDIR /app
RUN mkdir -p data && touch data/kb.ttl
CMD ["/usr/local/bin/rickview"]
```

**Comment by jsha** [comment]
Thanks for reporting! A couple of questions:

 - does this reproduce with another Rust http client in the same container?
 - if you write a minimal rust program that does just a DNS lookup, does
that also fail?

**Comment by KonradHoeffner** [comment]
I've now written a minimal Rust program with ureq at <https://github.com/KonradHoeffner/mwedns> that does indeed fail at the DNS lookup step:

```
$ git clone git@github.com:KonradHoeffner/mwedns.git --branch ureq
$ cd mwedns
$ docker build . -t mwedns
[...]
$ docker run --rm mwedns
Trying to resolve google.com with to_socket_addrs()
it worked
Trying to get google.com with ureq
it worked
Trying to resolve github.com with to_socket_addrs()
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Uncategorized, error: "failed to lookup address information: Name does not resolve" }', src/main.rs:8:51
```

## main.rs

```
use std::net::ToSocketAddrs;

fn main() {
    let domains = ["google.com", "github.com"];
    for domain in domains
    {
        println!("Trying to resolve {domain} with to_socket_addrs()");
        format!("{domain}:443").to_socket_addrs().unwrap();
        println!("it worked");
        println!("Trying to get {domain} with ureq");
        ureq::get(&format!("https://{domain}")).call().unwrap().into_reader();
        println!("it worked");
    }
}
```
If I interpret this correctly this is nothing that ureq can do about and I should report it somewhere else? Shall I still test it with another Rust http client?
