### ISSUE TITLE
Peer misbehaved: `ResumptionOfferedWithVariedCipherSuite`

### ISSUE THREAD

**Issue by laurmaedje** [algesten/ureq#657]
Requests spuriously fail for me with the error 
```
Connection Failed: tls connection init failed: peer misbehaved: ResumptionOfferedWithVariedCipherSuite
```
when trying to GET the URL `https://packages.typst.org/preview/index.json`

This seems to happen only after a few requests. It looks like the server tries to reuse a TLS session or something like that (_resumption offered_ at least indicates that to me)? Perhaps this could be fixed on my end by reusing a single agent, but I would have thought not reusing the client should only be a matter of performance, not correctness.

Note that this only happens with some servers. `packages.typst.org` is hosted on Azure Blob Storage with Azure Front Door CDN. It could also be a problem on Microsoft's end I guess.

Here is a reproduction:
```rust
fn main() {
    let url = "https://packages.typst.org/preview/index.json";
    for _ in 0..10 {
        let mut buf = vec![];
        let response = match ureq::get(url).call() {
            Ok(response) => response,
            Err(err) => panic!("failed: {err}"),
        };
        response.into_reader().read_to_end(&mut buf).unwrap();
        println!("Got {} bytes", buf.len());
    }
}
```

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x.

**Comment by laurmaedje** [comment]
Does 3.x fix this problem through some changes to TLS handling?

**Comment by algesten** [comment]
```rust
use std::io::Read;

fn main() {
    let url = "https://packages.typst.org/preview/index.json";
    for _ in 0..10 {
        let mut buf = vec![];
        let mut response = ureq::get(url).call().unwrap();
        response
            .body_mut()
            .as_reader()
            .read_to_end(&mut buf)
            .unwrap();
        println!("Got {} bytes", buf.len());
    }
}
```

Updated test code.

It gives me:

```
Got 278877 bytes
Got 279200 bytes
Got 279200 bytes
Got 279200 bytes
Got 279200 bytes
Got 279200 bytes
Got 279200 bytes
Got 279200 bytes
Got 279200 bytes
Got 279200 bytes
```

I think that means it works, right?

**Comment by laurmaedje** [comment]
Interestingly, the original snippet now also works for me (with ureq 2). It was always a bit flaky, but it's also possible that it was an Azure problem to begin with.

**Comment by algesten** [comment]
Oh well... computers 🤷  

:D
