### ISSUE TITLE
Update rustls for RISCV64 support

### ISSUE THREAD

**Issue by Xunop** [algesten/ureq#689]
Hello,
Could we consider updating `rustls` to version v0.21.8 or later? `rustls` v0.21.6 rely on `ring` v0.16.20,which has some problems with RISCV64 support, but these were fixed after v0.17. And `rustls` v0.21.8 is the first version that uses `ring` v0.17.0.  I have conducted tests by updating `rustls` to v0.21.9 and running the `test.sh` script, and it appears that no issues arise from this update.

**Comment by lolgesten** [comment]
Yeah, I'm happy to update `rustls`. The main problems is to keep `webpki`, `webpki-roots`, `rustls-native-certs` and `rustls` in lockstep. Sometimes one crate gets updated before the others, causing double deps. But if 0.21.8 has been out for a while, the others have probably had time to follow along.

**Comment by algesten** [comment]
In main

**Comment by Revertron** [comment]
> In main

Can we have a release on crates.io? :)

**Comment by algesten** [comment]
Yeah. I was waiting for #679 but there's not reason to hold up on that. I'll fix this weekend.
