### ISSUE TITLE
Upgrade webpki 0.19 -> 0.21

### ISSUE THREAD

**Issue by dbdr** [algesten/ureq#7]
Would you be able to upgrade the current dependency on webpki from 0.19 to the latest, 0.21? I'm getting version conflicts when combining with other crates that would be solved by this upgrade.

**Comment by lolgesten** [comment]
I'll try. I held it back because of clashing versions of ring.

**Comment by dbdr** [comment]
Thanks! Ring was also the crate that caused me issues, seems problematic as soon as any two crates use different versions.

Upgrade would be nice in any case, but don't go out of your way for this, right now this is not blocking me. I'm looking at attohttpc, since it did not have the ring issue, but I also found its API is closer to reqwest (.json().send() vs .send_json() in ureq for instance), and my main goal is to minimize the friction of the switch to a leaner HTTP client.

**Comment by dbdr** [comment]
Thanks!
