### ISSUE TITLE
Example of requesting a continuous stream

### ISSUE THREAD

**Issue by CarbonPool** [algesten/ureq#706]
I need to request an http address of type `multipart/x-mixed-replace`, he keeps returning streaming content, I didn't find how this library implements it, any help is greatly appreciated.

**Comment by algesten** [comment]
Hey @CarbonPool thank you for checking out ureq.

Have a look at [`Response::into_reader`](https://docs.rs/ureq/latest/ureq/struct.Response.html#method.into_reader) which allows you to stream a body.
