### ISSUE TITLE
Add support for configuring default headers in AgentBuilder

### ISSUE THREAD

**Issue by arihant2math** [algesten/ureq#732]
This would help if an agent builder wants to set a default set of headers (maybe an `Accept` header) which should persist across requests unless overwritten on a per-request basis, in a similar way to how user agents are managed currently. I’m happy to submit a pr.

**Comment by algesten** [comment]
Hi @arihant2math, welcome to ureq!

This is a function that's been asked for before, and we've rejected, see prior discussions:

https://github.com/algesten/ureq/issues/444
https://github.com/algesten/ureq/issues/308

Is there some use case you think we haven't considered there?
