### ISSUE TITLE
Potential to modify ordering for IS_TEST in lib module

### ISSUE THREAD

**Issue by wang384670111** [algesten/ureq#736]
https://github.com/algesten/ureq/blob/4e3169f212153f44d8ab58d174224e13fe1d0fa0/src/lib.rs#L479-L485

`SeqCst` is overly restrictive. I believe that the ordering can be appropriately modified.

In `lib` model, I believe that `IS_TEST` is merely signals for multithreading purposes and do not synchronize with other locals. Therefore, using `Relaxed` ordering should suffice.

(happy to make a PR if this looks reasonable)

**Comment by algesten** [comment]
Sure PR is good. Doesn't make any difference really since this is not a very used code path.
