### ISSUE TITLE
Add `Error::as_response`

### ISSUE THREAD

**Issue by k0nserv** [algesten/ureq#738]
Hello,

On `Error` there's currently a method called `into_response` which consumes the errors and converts it into a response, if the error occurred due to semantics of the response. However, this method consumes the errors and as such makes it impossible to e.g. check the status code while retaining the error.

The suggested `as_response` method would alleviate this by not consuming the error i.e.

```rust
  pub fn as_response(&self) -> Option<&Response> {
    todo!()
  }
```

Let me know if you like this idea and I can send a PR.

Thanks for your consideration

**Comment by algesten** [comment]
Hi @k0nserv!

**Comment by algesten** [comment]
The Error in str0m is an enum, you can match out the status without converting. We could of course make a helper.

**Comment by k0nserv** [comment]
Ah right, I'm just being a dummy 🤦‍♂️
