### ISSUE TITLE
Retry only idempotent requests

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#76]
At https://github.com/algesten/ureq/blob/master/src/unit.rs#L167, requests that fail on bad_status_read are retried, but only if no body bytes were sent. The [HTTP RFC says](https://tools.ietf.org/html/rfc7230#section-6.3.1):

>    A user agent MUST NOT automatically retry a request with a non-
   idempotent method unless it has some means to know that the request
   semantics are actually idempotent, regardless of the method, or some
   means to detect that the original request was never applied.

It's possible to have a POST request with an empty body; that would be non-idempotent, but would also have zero body bytes sent.

Relatedly, the comments in unit.rs discuss "body bytes sent" which suggests this code could be run if a request with a body was made, but the error happened before any bytes of the body were sent. However, body_bytes_sent is only set if the whole body is successfully sent. I think it would be clearer to run the retry only if body's size is set and is zero.

**Comment by algesten** [comment]
Interesting! Didn't realise the spec allowed for other mechanisms than just looking at the method.

I guess the simplest would be to just lock down any retries depending on method?

GET | HEAD | OPTIONS | TRACE | PUT | DELETE?

**Comment by jsha** [comment]
Yep, exactly. I have a branch in progress doing that that I'm hoping to upload today.
