### ISSUE TITLE
Include lib.rs docs from README.md

### ISSUE THREAD

**Issue by wiktor-k** [algesten/ureq#769]
Hi,

I was just browsing your project and noticed that you're generating `README.md` from `lib.rs`.

I wonder if you didn't want to do it the other way around - stuff content in `README.md` and just include it via `#![doc = include_str!("../README.md")]` like so: https://github.com/wiktor-k/testresult/blob/main/src/lib.rs#L1

The context is I noticed that the link to `AgentBuilder` [has been fixed in the template](https://github.com/algesten/ureq/commit/fbdeca8702c745408528cacbe35efa1da1719ed0) but this change has not been propagated to the README.md (I guess `cargo readme` has not been run?). Doing it via lib.rs includes could avoid this "split brain" problem.

If this doesn't sound like something useful feel free to close the issue.

Have a nice day! :wave:

**Comment by algesten** [comment]
I'm quite happy the way it works. Thanks!
