### ISSUE TITLE
any plans regarding ureq 2.10.1 release

### ISSUE THREAD

**Issue by swanandx** [algesten/ureq#770]
There is a commit ( https://github.com/algesten/ureq/commit/76cb6715d1d4bf291e8fb1d4cc2fbdc700623dcc ) related to version 2.10.1, but it isn't released.

Is there any plans to release it? ( asking so that we can get around `no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point` issue 😅 )

**Comment by algesten** [comment]
Sorry. Got sidetracked with ureq 3.x. It's published now.

**Comment by swanandx** [comment]
Thank you so much!
