### ISSUE TITLE
3.x regression: casing of header names is not preserved

### ISSUE THREAD

**Issue by laniakea64** [algesten/ureq#776]
In `ureq` 2.10, HTTP header names are sent exactly as specified by the user.  This is good :+1: 

In `ureq` 3.x, HTTP header names are normalized to all-lowercase when sent.

I know HTTP header names are _supposed_ to be case-insensitive, but this isn't always actually true: libraries normalizing header case is known to break some uses (e.g. [[1]](https://github.com/seanmonstar/reqwest/issues/402), [[2]](https://github.com/seanmonstar/reqwest/discussions/1660)).

For feature parity with `ureq` 2.10, could `ureq` 3.x please offer some way to case-sensitively specify how individual header names will be sent?

Thanks!

**Comment by algesten** [comment]
Great feedback!

This will sadly not be possible in ureq 3.x. The handling of headers is completely delegated to the [http crate](https://crates.io/crates/http) I believe they internally normalize all headers to lowercase to not have to allocate strings for well known headers.

**Comment by algesten** [comment]
> Is `http` crate also responsible for sending request headers over the network? If not, could it be possible to apply custom normalization of header name case when sending request headers? Such setting at the level of the `ureq::Agent` would cover my usage.

The http crate is simply pretty much only types for stuff like `Request`, `Response`,  `HeaderName` and `HeaderValue`. It doesn't have any IO or concern itself with how requests/responses are serialized over the wire. So the network part is on ureq's side.

I'm however keen to delegate all header value compliance, etc to the http crate, and not have to maintain double implementation.

**Comment by algesten** [comment]
> Could you please point me to the `ureq` 3.x code where `ureq` sends the headers over the network? Would be interested in experimenting with patching locally to send some headers with custom casing. Thanks!

It's a bit involved :) 

I've made this subcrate called `hoot` which tries to encode the HTTP/1.1 protocol in a correct way Sans-IO. [This example](https://docs.rs/hoot/0.2.1/hoot/client/index.html#example) gives you an idea of what it's doing.

Unsure how valuable it will be for hacking, but the code you're asking for is here: https://github.com/algesten/hoot/blob/main/hoot/src/client/call.rs#L407-L428

You effectively need a way to preserve the header case all through ureq/Unit -> hoot/Flow -> hoot/Call
