### ISSUE TITLE
Timeouts for DNS lookups

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#79]
Right now ureq has no way to time out DNS lookups. It uses [to_socket_addrs](https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html#tymethod.to_socket_addrs), which says:

> Note that this function may block the current thread while resolution is performed.

Under the hood, I believe this uses [getaddrinfo](https://www.man7.org/linux/man-pages/man3/getaddrinfo.3.html) on Linux, which does not allow setting a timeout.

Some documentation about how curl handles this is here: https://github.com/curl/curl/blob/26d2755d7c3181e90e46014778941bff53d2309f/lib/hostip.c#L91-L115. It sounds like the options are:

 - Use an asynchronous resolver (probably not an option for us).
 - Run the resolve in a thread. Currently the only place ureq uses threads outside of tests is when handling a socks stream, and there's a comment on that code that suggests it would be better to set a read timeout on the upstream socks implementation. But some judicious use of threads in ureq is probably not a bad idea.
 - Use [alarm()](https://www.man7.org/linux/man-pages/man2/alarm.2.html) / SIGALRM. It can only set alarms in units of seconds, and curl  mentions there might be some compatibility problems due to running the rest of the program in a signal handler: https://github.com/curl/curl/blob/26d2755d7c3181e90e46014778941bff53d2309f/lib/hostip.c#L625-L637

This may not be a terribly big priority because in practice getaddrinfo does have built-in timeouts on many systems. For instance, on Linux the [default config has a timeout of 5s for name resolution](https://man7.org/linux/man-pages/man5/resolv.conf.5.html). The [Windows default is 15s](https://marktugbo.com/2019/04/29/how-to-increase-dns-timeout-value/).

**Comment by algesten** [comment]
Related to #618

**Comment by algesten** [comment]
This is solved in ureq 3.x
