### ISSUE TITLE
Feature request: ability to clear the pool

### ISSUE THREAD

**Issue by sosthene-nitrokey** [algesten/ureq#810]
There are some situations (firewall for example), where it is desirable to clear all connections in the pool. For example after a IO error in a request, one might want to clear all the connections in the pool to ensure that the error was not due to the connection being stale.

This feature request would be to add the following method to `Agent`:

```rust
    /// Remove all idle connections from the pool
    ///
    /// Requests after this being called will use a fresh connection.
    ///
    /// Requests that terminate after this call will be added to the pool.
    pub fn clear_pool(&self);
```

See [this implementation](https://github.com/Nitrokey/ureq/pull/4) for our own fork of ureq based on the 2.0 branch.

**Comment by algesten** [comment]
Interesting!

The last thing I did was to make it possible to override the [AgenConfig settings per request](https://github.com/algesten/ureq/blob/main/src/request.rs#L122).

It strikes me that this is somewhat related to the `max_idle_age` setting. Meaning if you set that to 0, you should get a fresh connection every time. We should maybe tweak the internals a bit to ensure this is indeed the behavior we get.

**Comment by sosthene-nitrokey** [comment]
That's great, but I don't think this solves this case. Sometimes you would know that no requests will happen for a while and want to close idle connections to not waste resources, and sending a new request with `max_idle_age` to `zero` for that seems wasteful.

**Comment by sosthene-nitrokey** [comment]
There is no `AgentConfig` in the released ureq. Is it a 3.0 thing?

In 2.x the current AgentBuilder is not clonable.

There is also the issue that if the agent is cloned around, changing the agent needs an additional mechanism to ensure all instances are modified too. Something like arc-swap.

**Comment by algesten** [comment]
Sorry, yeah. My mind is in 3.x land.

**Comment by sosthene-nitrokey** [comment]
I haven't tried using implementing it, but having a cheaply cloneable agent config to be able to easily re-create clients when needed should work, the only downside being needing an `ArcSwap` more, which is fine.

**Comment by algesten** [comment]
Cool, thanks!
