### ISSUE TITLE
Missing argument for CookieStore::new()

### ISSUE THREAD

**Issue by jullanggit** [algesten/ureq#836]
I am currently trying out the 3.0.0-rc1, but when trying to compile i get the following error: 
```error[E0061]: this function takes 1 argument but 0 arguments were supplied
   --> /home/user/.cargo/git/checkouts/ureq-cb1f1b767b8d67d8/014b8f6/src/cookies.rs:147:31
    |
147 |             inner: Mutex::new(CookieStore::new()),
    |                               ^^^^^^^^^^^^^^^^-- argument #1 of type `std::option::Option<publicsuffix::List>` is missing
    |
note: associated function defined here
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cookie_store-0.21.0/src/cookie_store.rs:495:12
    |
495 |     pub fn new(
    |            ^^^
help: provide the argument
    |
147 |             inner: Mutex::new(CookieStore::new(/* std::option::Option<publicsuffix::List> */)),
    |                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This happens on the rc, as well as on the main git branch. This could totaly be some kind of issue on my side, but I thought I'd let you know. Thanks in advance for your response!
## Edit
When testing this in isolation i couldn't replicate this issue, even when using the same features. Deleting the Cargo.lock also didnt resolve this. 
The repo im having this issue with is https://github.com/jullanggit/tam_intranet

**Comment by lolgesten** [comment]
Excellent! 

Thank you so much. I'll dig into this.

**Comment by jullanggit** [comment]
Thank you for looking into this, after some more experimentation, it seems like removing the explicit cookie_store dependency resolved this issue.
