### ISSUE TITLE
ureq 3 does not permit custom Response bodies in Middleware

### ISSUE THREAD

**Issue by kade-robertson** [algesten/ureq#839]
At least, I can't seem to figure out a way to do this at the moment. For context, I have a project where I implement a caching middleware to allow me to store responses, as they are essentially permanently cache-able. I have some very rudimentary logic to do this with the current 2.x releases here: https://github.com/kade-robertson/ddragon/blob/master/src/cache_middleware.rs

I'm working on updating this to 3.x, but this is the last piece I can't replicate (in-progress branch here: https://github.com/kade-robertson/ddragon/tree/ureq-3.x).

Ideally, this would also mean the previous limitation I had (UTF-8 text only response caching, though I think this was previously solved with the `http-interop` feature I added and just.. never updated my other work with it) would _also_ be resolved, so I could avoid the odd logic I have for caching things like images. If this was flexible enough, it could mean something like [http-cache](https://github.com/06chaynes/http-cache) could get a `ureq` implementation.

Related: https://github.com/algesten/ureq/issues/589 (wasn't sure if it made sense to re-open this)

**Comment by algesten** [comment]
Excellent feedback, thanks!

I realise I made a big omission here not letting users construct the response bodies. I will fix this. Thank you so much for testing and reporting.

**Comment by algesten** [comment]
Hi @kade-robertson I believe I merged a fix for this in main now. You should find a `Body::builder()` that gives you a way to construct `Body` yourself.
