### ISSUE TITLE
Provide a way to disable `tls12` feature for rustls

### ISSUE THREAD

**Issue by andylizi** [algesten/ureq#842]
ureq is a lightweight HTTP client often used to communicate with one or a few hardcoded servers (e.g. making API calls). TLS 1.2 support is mostly unnecessary in those situations because we can know for sure if the hardcoded servers support TLS 1.3[^1] or not. 

TLS 1.2 in rustls often requires separate code paths to handle. Disabling the `tls12` feature can reduce binary size by ~100kb. It'd be great if ureq can provide a way to do so.

[^1]: Which is also highly likely, as 70% of sites now support TLS 1.3 according to https://www.ssllabs.com/ssl-pulse/

**Comment by algesten** [comment]
Me testing to do a simple binary with/without tls12 enabled.

```
-rwxr-xr-x   1 martin  staff  2714424 Oct  8 18:19 foo-no-tls12*
-rwxr-xr-x   1 martin  staff  2821384 Oct  8 18:21 foo-with-tls12*
```

**Comment by algesten** [comment]
(2821384-2714424)/2821384 = 0.038

So tls12 takes 3.8% of a macOS binary. Now, the question is: the complication of having this as a separate feature, is it worth 3.8% potential reduction in size?

**Comment by algesten** [comment]
This complicates the feature flag situation for a rather small gain. I don't want this, for now.
