### ISSUE TITLE
cannot `send_json` from `ureq::delete()`

### ISSUE THREAD

**Issue by m4rch3n1ng** [algesten/ureq#853]
trying to run `ureq::delete().send_json()?` does not compile with ureq 3.

```rust
use serde::Serialize;

#[derive(Serialize)]
struct Test;

fn main() {
	let data = Test;
	let thing = ureq::post("https://example.org").send_json(&data);
	// this line does not compile
	//       no method named `send_json` found: ----vvvvvvvvv
	let thing = ureq::delete("https://example.org").send_json(&data);
}
```

this is probably intentional, as the error explicitly points out that it doesn't work with requests that are `WithoutBody`, only ones that are `WithBody`.

![image](https://github.com/user-attachments/assets/6ccc62b3-b61c-43c5-a6b7-cb6ec2165d8b)

but it makes a bunch of apis unusable with ureq 3, as, for example, deleting an item from a spotify playlist requires you to send a json body with a http `DELETE` request. https://developer.spotify.com/documentation/web-api/reference/remove-tracks-playlist.

**Comment by algesten** [comment]
@m4rch3n1ng oh wow! TIL!

The specs say DELETE does not have a body, so I went with that. But of course there's the spec and then there's reality :)

I probably need to make some escape hatch to be able to provide a body with ANY method.

Thank you so much for taking the time to find this. Fix will be coming before rc2!

**Comment by algesten** [comment]
This should be fixed in main now.
