### ISSUE TITLE
Cant seem to get cookies to work

### ISSUE THREAD

**Issue by jullanggit** [algesten/ureq#862]
## Setup
I am trying to authenticate with a website, using cookies. I have the crate feature cookies enabled. 
## Issue
After doing the request, it doesn't seem like I am authenticated, and doing `agent.cookie_jar().iter().for_each(|cookie| println!("{}:{}", cookie.name(), cookie.value()));` doesn't print anything. Am I doing something wrong?
## Response
```
Response { 
    status: 200,
    version: HTTP/1.1,
    headers: {
        "date": "Tue, 15 Oct 2024 21:45:34 GMT",
        "content-type": "text/html; charset=UTF-8",
        "transfer-encoding": "chunked",
        "connection": "keep-alive",
        "x-powered-by": "PHP/8.1.26",
        "set-cookie": "sturmsession=d1d79ba6d9feaffd87482f08ff268d97; path=/; secure; HttpOnly; SameSite=None",
        "pragma": "no-cache",
        "x-page-speed": "1.13.35.2-0",
        "cache-control": "max-age=0, no-cache, no-store",
        "strict-transport-security": "max-age=31536000; includeSubDomains",
    },
    body: Body,
}
```

**Comment by algesten** [comment]
Ooof! Good catch!

I'll get this sorted ASAP!

**Comment by jullanggit** [comment]
Thank you!

**Comment by jullanggit** [comment]
Thanks for fixing it this fast! (well, when the PR gets merged)

**Comment by algesten** [comment]
Thank you for taking the time to test and report it!
