### ISSUE TITLE
Feature request: ability to remove the default "Accept" and "Accept-Encoding" headers completely.

### ISSUE THREAD

**Issue by MaximalCats** [algesten/ureq#865]
Currently, the "Accept" and "Accept-Encoding" headers are hard coded in for each request (source: https://github.com/algesten/ureq/blob/b1b6458087ebb05775102b65b7ebcfc6de148cbc/src/run.rs#L287).

It would be useful to have the option to disable this behaviour.

**Comment by algesten** [comment]
You can always override them with the value you want. Are there cases where having them would cause problems?

**Comment by algesten** [comment]
> I realize now afterwards this probably doesn't fit the project's goal of being simple.

Supporting broken servers is just the way it goes :)

Wonder if there is a case to be made for that any of the automatic headers ureq maintains can be set to empty string to omit entirely? Magic values are not great, but is it worse or better than having config options for all of them? 🤔
