### ISSUE TITLE
Ureq 3.x: add a `send_empty` method `RequestBuilder<WithoutBody>` that forwards to `call`

### ISSUE THREAD

**Issue by sosthene-nitrokey** [algesten/ureq#868]
While it is nice to have the type safety when creating requests, the distinction when creating a GET request without a body and a POST request without a body makes it harder when using code generation such as OpenAPI.

**Comment by algesten** [comment]
Is [`force_send_body`](https://docs.rs/ureq/3.0.0-rc2/ureq/struct.RequestBuilder.html#method.force_send_body) an alternative here? Ideally I'd like to not pollute the API with "useless" functions.

**Comment by sosthene-nitrokey** [comment]
It is. But it seems a bit weird to use it for that.

Another possibility would be to rename `send_empty` to `call()`.

**Comment by algesten** [comment]
What about renaming `force_send_body` to something like  `erase_typestate` (or similar) and introduce a new state `Any`, that has a single API? I think it would be entirely a surface change.

**Comment by algesten** [comment]
@sosthene-nitrokey another thought on this one. What about using only the `http` crate API and `Agent::run` thus circumventing the need completely?

**Comment by algesten** [comment]
Alright. Thanks. Since you got a solve, and I on balance like the API the way it is, I'll close this.
