### ISSUE TITLE
Ureq 3.x.x TlsConfigBulder::disable_verification(true) should not set supported signature schemes to an empty array

### ISSUE THREAD

**Issue by sosthene-nitrokey** [algesten/ureq#869]
https://github.com/algesten/ureq/blob/de4f0fb8bf5b666d20e420b7ae35a6f31c800544/src/tls/rustls.rs#L243

Since the disabled verifier accepts any certificate and any signature, it should instead return an array of all defined signature algorithms. Otherwise the other end will reject the handshake.

**Comment by algesten** [comment]
Oops! Yep. Must be done!
