### ISSUE TITLE
Response reader shouldn't unchunk

### ISSUE THREAD

**Issue by alex-kattathra-johnson** [algesten/ureq#875]
To better simulate how curl works, I think the `response.into_reader` shouldn't unchunk the response, but should spit them out as they arrive. For example, if I were to do `/api/v1/namespaces/default/pods?watch=true` on the k8s API, it should return the chunks of watch events as they are seen. If this is not the default behavior there should at least be an option to do so.

**Comment by algesten** [comment]
Hi @alex-kattathra-johnson and welcome to ureq!

Let me make sure I get this correctly. For this API endpoint, you get a chunked response, and each event arrives as a separate chunk, meaning you do want to unchunk (remove the chunk length headers etc), but make sure the reader returns decoded chunk-by-chunk meaning you effectively get event-by-event?

**Comment by alex-kattathra-johnson** [comment]
Exactly! This endpoint doesn't have an end, but keeps sending events chuck by chunk. Also, I see that there's a 3.0 rc on the way! Awesome!

**Comment by algesten** [comment]
Interesting problem!

It's a bit of a weird use of chunked transfer. It's pushing application-level semantics to the transport level. I haven't studied the spec for this, but I wouldn't be surprised if a proxy could rechunk/fragment the input into something else breaking the assumption 1 chunk = 1 event.

Given that, I think the `Read` trait maybe isn't the correct abstraction for this. That trait assumes you could use a small buffer (even reading byte-by-byte). If the user provided a too small buffer forcing the Read trait to fragment, the function would need to Error (or something).

Maybe a better way would be `impl Iterator<Item=&mut dyn Read>` where each `Item` corresponds to one chunk (something like `into_chunk_iter()`).

**Comment by alex-kattathra-johnson** [comment]
That is the way kubernetes currently sends out watch events, but it doesn't seem like a weird use of a RESTAPI with a chunked response. Seems like a socket would be a better way to do it. I like the idea of using a `into_chunk_iter` iterator.

**Comment by alex-kattathra-johnson** [comment]
It actually looks like the kubernetes API does upgrade to a websocket if the `upgrade` header is specified. So this isn't very important, especially since http/2 doesn't support the `Transfer-Encoding` header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding).
