### ISSUE TITLE
Ureq 3.x: keep the ability to get response uri

### ISSUE THREAD

**Issue by Rileran** [algesten/ureq#883]
In ureq 2.x, the `get_url` method on the `Response` struct allowed to get the final uri used in case of HTTP redirect.

With the use of the `http` crate, this feature is gone because the `Response` object does not keep the uri. I think it may be possible to use the `Extension` feature of the `http` crate to bring back this feature. Would you be interested in a PR?

For reference, this mechanism is currently used by `reqwest` to provide this feature: https://github.com/seanmonstar/reqwest/blob/e2d4b14c695acaebe531af7ce4712e182278f38a/src/response.rs

**Comment by algesten** [comment]
Closed by #884.

Thanks!
