### ISSUE TITLE
Git tag and changelog entries missing for v2.11.0

### ISSUE THREAD

**Issue by edmorley** [algesten/ureq#902]
Hi - thank you for your work on ureq!

We just had Dependabot open PRs to update our dependencies on ureq, however, the Dependabot PR description doesn't include what's changed - since it relies upon the Git tag and also changelog entries themselves to be populated.

Would it be possible to add `v2.11.0` to `CHANGELOG.md` on both the `main` branch and the `2.x` branch:
https://github.com/algesten/ureq/blob/main/CHANGELOG.md
https://github.com/algesten/ureq/blob/2.x/CHANGELOG.md

And to add a Git tag for the release?
https://github.com/algesten/ureq/tags

Many thanks

**Comment by algesten** [comment]
> Hi - thank you for your work on ureq!

Thanks!

> Would it be possible to add v2.11.0 to CHANGELOG.md on both the main branch and the 2.x branch:

Oh sorry. I never pushed the tag. I'll add the changelog entry now.

**Comment by algesten** [comment]
This is fixed in the 2.x branch. Next up I'll fix it in main.

**Comment by algesten** [comment]
Done in #902 and #903

**Comment by edmorley** [comment]
Many thanks!
