### ISSUE TITLE
Couldn't specify a root cert for a proxy

### ISSUE THREAD

**Issue by prettyroseslover** [algesten/ureq#909]
Hello!
I use this crate to send simple GET-requests to a server through a proxy, which works perfectly fine. However, as I tried to add a root cert (PEM) to a proxy - I couldn't make it work.

> PS. I use [3proxy](https://github.com/3proxy/3proxy) with the following config file:
> ```
> plugin "C:\Users\user\Downloads\3proxy-0.9.4\bin\SSLPlugin.dll" ssl_plugin
> ssl_certcache "C:\Users\user\Downloads\3proxy-0.9.4\bin\cert\"
> ssl_mitm
> proxy -p3129 -i192.168.0.172 -l
> ```
> Proxy works just fine as I check it with `curl -x http://192.168.0.172:3129 <whatever_url_to_get> --cacert /home/user/3proxy.pem`
>

That's what I tried at first: 
```rust
            let mut handler = ureq::AgentBuilder::new();
            
            let url = "whatever_url_to_get".to_string();
            let proxy = "http://192.168.0.172:3129".to_string();

            let cert = CertificateDer::from_pem_file(PathBuf::from("/home/user/3proxy.pem")).unwrap();
            let mut root_store = RootCertStore::empty();
            root_store.add(cert).unwrap();
            let tls_config =
                rustls::ClientConfig::builder()
                    .with_root_certificates(root_store)
                    .with_no_client_auth();
            handler = handler.tls_config(Arc::new(tls_config));

            let proxy = ureq::Proxy::new(proxy).unwrap();
            handler = handler.proxy(proxy);
            let request = handler.build().get(&url);
            request.call()           
```
However no matter how hard I tried the response was always the same: `Status(400, Response[status: 400, status_text: BadRequest, url: whatever_url_to_get])`

Then I tried to switch to `native_tls`:
```rust
// i'm leaving out the same handler building stuff
            let bytes = include_bytes!("/home/user/3proxy.pem");
            let cert = native_tls::Certificate::from_pem(bytes).unwrap();

            let connector = native_tls::TlsConnector::builder()
                .add_root_certificate(cert)
                .build()
                .unwrap();

            let tls_connector = Arc::new(connector);
            handler = handler.tls_connector(tls_connector.clone());
```
Got 400 Response once again.

I also tried `ureq-3.0.0-rc3` however with it I couldn't even set up the proxy, always getting `Err(Io(Custom { kind: InvalidData, error: InvalidMessage(InvalidContentType) }))`

So out of desperation I decided to submit this issue as I could not wrap my head around this problem or fix it in any way. Maybe there's a deeper issue I don't see?

Thank you!

**Comment by algesten** [comment]
@prettyroseslover this was completely broken in ureq 3.x. I think it's closed in the main branch. Thanks!
