### ISSUE TITLE
request: re-consider the ConfigBuilder .user_agent() parameter change in 3.0.0-rc3

### ISSUE THREAD

**Issue by Swarkin** [algesten/ureq#911]
Starting 3.0.0-rc3, the user_agent (for example) received a change in the parameter type from `Option` to `AutoHeaderValue`.
I personally strongly prefer the old method as it is way simpler and the current one is very confusing.

From:
![image](https://github.com/user-attachments/assets/6548c01e-41ff-4adb-9285-208aecce9188)
To:
![image](https://github.com/user-attachments/assets/325c54fc-6852-456f-a998-189288e91eea)

The AutoHeaderValue and Arc stuff could also be abstracted away into the internals to make the api a little more beginner friendly and nicer to look at.

**Comment by algesten** [comment]
Hi @Swarkin, welcome to ureq!

Notice that the `.user_agent()` takes `impl Into<AutoHeaderValue>`, which means it's very liberal with what it expects.

You can actually write `.user_agent("hello")` and it should work.

This could potentially be pointed out more clearly in the docs.

**Comment by Swarkin** [comment]
It doesn't seem to accept `Into<AutoHeaderValue>`:
![image](https://github.com/user-attachments/assets/cc003643-09e1-4bf1-8f7d-7b07001c99a5)
https://docs.rs/ureq/3.0.0-rc3/ureq/config/struct.ConfigBuilder.html#method.user_agent

**Comment by algesten** [comment]
Oh. Sorry! It's in main. No the rc3

```
* 0664b5a Abdul Rahman Sibahi improve ergonomics around AutoHeaderValue
* 3e7d6bb Martin Algesten Fix clippy
* cfb18ba Martin Algesten Add doc for test fn
* 8231cf8 Martin Algesten (tag: 3.0.0-rc3) 3.0.0-rc3
```

**Comment by Swarkin** [comment]
I'll be sticking to rc2 for now then! Thanks for the quick responses.
