### ISSUE TITLE
header: disallow white space between field name and colon

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#96]
https://tools.ietf.org/html/rfc7230#section-3.2.4
>    No whitespace is allowed between the header field-name and colon.  In
   the past, differences in the handling of such whitespace have led to
   security vulnerabilities in request routing and response handling.  A
   server MUST reject any received request message that contains
   whitespace between a header field-name and colon with a response code
   of 400 (Bad Request).  A proxy MUST remove any such whitespace from a
   response message before forwarding the message downstream.

**Comment by algesten** [comment]
I'm all in!
