### ISSUE TITLE
style: empty comment lines?

### ISSUE THREAD

**Issue by jsha** [algesten/ureq#97]
I had a question about coding style. I noticed there are a bunch of empty comments, like so:

```
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        //
        let line = s.to_string();
```

Are these meant to denote something? Should I clean them up?

**Comment by algesten** [comment]
@jsha this is a quirk I have. 🙈 

I use `cargo fmt` bound to quick-keys in my editor, and I use it all the time, however I have a love/hate relationship to code formatters. One thing I can't quite abide by is not allowing me to have some space between the function declaration and the first row. I struggle to see where the declaration ends and the code starts.

I'm not going to be precious about them however. It's a shared code base and it's better without my idiosyncrasies. Remove if you want!

**Comment by jsha** [comment]
No problem! I am a big fan of `cargo fmt`.
